"""Trusted archive-backed execution for the pinned m2c decompiler.

The historical m2c provider accepts a caller callback.  That is useful for
unit tests, but it is not a production boundary: a callback can inspect the
checkout, choose a different command, or return a fabricated source file.  The
executor in this module consumes one immutable :class:`M2CRevisionPin`, one
typed :class:`M2CInvocation`, and only bytes verified by the run archive.

Every external m2c call is preceded by a durable request document.  Completed
requests are replayed from their immutable result document, while a request
with no result is returned as a typed pending handoff.  Reconstruction only
verifies archive objects and identities.  It never invokes m2c and never writes
the archive.
"""

from __future__ import annotations

import io
import json
import math
import os
import re
import shutil
import stat
import subprocess
import sys
import tarfile
import tempfile
import zipfile
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path, PurePosixPath
from types import MappingProxyType
from typing import Any, Optional

try:
    from .m2c_revision_matrix import M2C_MATRIX_PROTOCOL, M2CRevisionPin
    from .m2c_revision_provider import (
        CURRENT_M2C_REVISION,
        M2CInvocation,
        M2CDraftPayload,
        M2CProviderError,
        M2CRevisionIdentity,
    )
    from .search_archive import ArchiveError, ContentAddressedArchive
    from .search_types import (
        ArtifactRef,
        canonical_bytes,
        hash_bytes,
        hash_canonical,
        validate_hash,
        validate_relative_path,
    )
except ImportError:  # pragma: no cover - direct automation invocation
    from m2c_revision_matrix import M2C_MATRIX_PROTOCOL, M2CRevisionPin  # type: ignore
    from m2c_revision_provider import (  # type: ignore
        CURRENT_M2C_REVISION,
        M2CInvocation,
        M2CDraftPayload,
        M2CProviderError,
        M2CRevisionIdentity,
    )
    from search_archive import ArchiveError, ContentAddressedArchive  # type: ignore
    from search_types import (  # type: ignore
        ArtifactRef,
        canonical_bytes,
        hash_bytes,
        hash_canonical,
        validate_hash,
        validate_relative_path,
    )


M2C_EXECUTOR_PROTOCOL = "sotn-m2c-revision-executor-v1"
M2C_RUNTIME_PROTOCOL = "sotn-m2c-revision-runtime-v1"
M2C_PREFLIGHT_PROTOCOL = "sotn-m2c-revision-preflight-v1"
M2C_REQUEST_PROTOCOL = "sotn-m2c-revision-request-v1"
M2C_RESULT_PROTOCOL = "sotn-m2c-revision-result-v1"
M2C_SCRATCH_PROTOCOL = "sotn-m2c-revision-scratch-v1"
M2C_PIN_PROTOCOL = M2C_MATRIX_PROTOCOL + ":pin"

MODULE_IDENTITY = hash_canonical(
    {
        "module": "automation.m2c_revision_executor",
        "protocol": M2C_EXECUTOR_PROTOCOL,
        "version": "1.0.0",
    }
)

# These are the only target triples accepted by the production m2c boundary.
# m2c has no Saturn/SH backend, so Saturn intentionally maps to no command.
M2C_TARGET_MAP = MappingProxyType(
    {
        "us": "mips-ido-c",
        "hd": "mips-ido-c",
        "pspeu": "arm-gcc-c",
        "saturn": None,
    }
)

_PLATFORM_POSIX = "native-posix"
_PLATFORM_WSL = "windows-wsl"
_SUPPORTED_PLATFORMS = frozenset(M2C_TARGET_MAP)
_SOURCE_PREFIX = "artifacts/m2c-revision-sources/"
_TOOL_PREFIX = "artifacts/m2c-revision-tools/"
_INPUT_PREFIX = "artifacts/"
_DRAFT_PREFIX = "artifacts/m2c-drafts/"
_OUTPUT_PREFIX = "artifacts/m2c-executor-output/"
_REQUEST_CATEGORY = "m2c-executor-requests"
_RESULT_CATEGORY = "m2c-executor-results"
_SCRATCH_ROOT = "m2c-executor-scratch"
_MAX_TIMEOUT_SECONDS = 3600.0
_MAX_PREFLIGHT_TIMEOUT_SECONDS = 30.0
_MAX_OUTPUT_BYTES = 16 * 1024 * 1024
_MAX_SOURCE_BYTES = 16 * 1024 * 1024
_MAX_CONTEXT_BYTES = 8 * 1024 * 1024
_MAX_CONTEXTS = 64
_MAX_SWITCHES = 32
_MAX_TOOL_BYTES = 64 * 1024 * 1024
_MAX_TOOL_FILES = 4096
_MAX_RECORD_BYTES = 2 * 1024 * 1024

# Only no-argument options are admitted from the typed invocation.  Target,
# function, context, and filename arguments are always generated by this
# module.  In particular, arbitrary option strings are not a command API.
_ALLOWED_SWITCHES = frozenset(
    {
        "--stack-structs",
        "--debug",
        "--stacktrace",
        "--print-assembly",
        "--sanitize-tracebacks",
        "--valid-syntax",
        "--allman",
        "--knr",
        "--indent-switch-contents",
        "--unk-underscore",
        "--hex-case",
        "--no-casts",
        "--zfill-constants",
        "--force-decimal",
        "--deterministic-vars",
        "--descending-regs",
        "--backwards-bss",
        "--stop-on-error",
        "--void",
        "--gotos-only",
        "--no-ifs",
        "--no-switches",
        "--no-andor",
        "--no-unk-inference",
        "--no-stack-spill",
        "--heuristic-strings",
        "--pdb-translate",
        "--disable-gc",
    }
)


class M2CExecutorError(ValueError):
    """Base class for immutable binding and execution failures."""

    code = "m2c_executor_error"
    status = "invalid"

    def __init__(self, detail: str, *, code: Optional[str] = None) -> None:
        super().__init__(detail)
        if code:
            self.code = code
        self.detail = detail


class M2CExecutorInputError(M2CExecutorError):
    """A serialized binding or invocation is malformed or forged."""

    code = "m2c_executor_input_invalid"


class M2CExecutorUnavailable(M2CExecutorError):
    """The trusted pinned runner cannot execute on this platform."""

    code = "m2c_executor_unavailable"
    status = "unavailable"


class M2CExecutorRefused(M2CExecutorError):
    """The pinned m2c runner rejected a bounded invocation."""

    code = "m2c_executor_refused"
    status = "refused"


class M2CExecutorTimeout(M2CExecutorError):
    """The pinned runner exceeded the immutable wall-clock bound."""

    code = "m2c_executor_timeout"
    status = "timeout"


class M2CExecutorInvalidResponse(M2CExecutorError):
    """The pinned runner returned malformed or over-sized output."""

    code = "m2c_executor_invalid_response"
    status = "invalid"


class M2CExecutorInapplicable(M2CExecutorError):
    """The real pinned tool has no backend for the requested platform."""

    code = "m2c_target_inapplicable"
    status = "inapplicable"


class M2CExecutorPending(M2CExecutorError):
    """A durable request exists without a terminal result."""

    code = "m2c_request_pending"
    status = "pending"


def _strict_mapping(value: Any, fields: Sequence[str], label: str) -> dict[str, Any]:
    if not isinstance(value, Mapping):
        raise M2CExecutorInputError(f"{label} must be an object")
    data = dict(value)
    if any(not isinstance(key, str) for key in data):
        raise M2CExecutorInputError(f"{label} keys must be text")
    required = set(fields)
    missing = required.difference(data)
    unknown = set(data).difference(required)
    if missing:
        raise M2CExecutorInputError(
            f"{label} is missing fields: {', '.join(sorted(missing))}"
        )
    if unknown:
        raise M2CExecutorInputError(
            f"{label} has unknown fields: {', '.join(sorted(unknown))}"
        )
    return data


def _identity(value: Any, label: str) -> str:
    try:
        return validate_hash(value, label)
    except Exception as exc:
        raise M2CExecutorInputError(f"{label} must be a sha256 identity") from exc


def _artifact(value: Any, label: str) -> ArtifactRef:
    try:
        item = value if isinstance(value, ArtifactRef) else ArtifactRef.from_dict(value)
    except Exception as exc:
        raise M2CExecutorInputError(f"{label} is not an ArtifactRef") from exc
    if "\\" in item.path:
        raise M2CExecutorInputError(f"{label} must use POSIX separators")
    try:
        validate_relative_path(item.path, label)
    except Exception as exc:
        raise M2CExecutorInputError(f"{label} is not a safe relative path") from exc
    return item


def _artifact_identity(value: Optional[ArtifactRef]) -> Optional[dict[str, Any]]:
    return None if value is None else value.to_dict()


def _bounded_bytes(
    value: Any,
    label: str,
    maximum: int,
    *,
    allow_empty: bool = False,
    reject_nul: bool = True,
) -> bytes:
    if not isinstance(value, bytes):
        raise M2CExecutorInputError(f"{label} must be bytes")
    if not allow_empty and not value:
        raise M2CExecutorInputError(f"{label} must be nonempty")
    if len(value) > maximum:
        raise M2CExecutorInputError(f"{label} exceeds its immutable bound")
    if reject_nul and b"\x00" in value:
        raise M2CExecutorInputError(f"{label} contains NUL bytes")
    return value


def _archive_bytes(
    archive: ContentAddressedArchive,
    reference: ArtifactRef,
    label: str,
    *,
    prefix: str,
    maximum: int,
    allow_empty: bool = False,
    reject_nul: bool = True,
) -> bytes:
    reference = _artifact(reference, label)
    if not reference.path.startswith(prefix):
        raise M2CExecutorInputError(f"{label} is outside its pinned archive prefix")
    try:
        data = archive.verify(reference)
    except (ArchiveError, OSError, TypeError, ValueError) as exc:
        raise M2CExecutorInputError(f"{label} is missing or corrupt") from exc
    return _bounded_bytes(
        data,
        label,
        maximum,
        allow_empty=allow_empty,
        reject_nul=reject_nul,
    )


def _platform() -> str:
    return _PLATFORM_WSL if _is_windows_host() else _PLATFORM_POSIX


def _is_windows_host() -> bool:
    """Return the host mode without mutating ``os.name`` in callers/tests."""

    return os.name == "nt"


def _target_for(platform: str) -> Optional[str]:
    try:
        return M2C_TARGET_MAP[platform]
    except KeyError as exc:
        raise M2CExecutorInputError("m2c platform is unsupported") from exc


def _recipient_parts(recipient_id: str) -> tuple[str, str]:
    if not isinstance(recipient_id, str):
        raise M2CExecutorInputError("m2c recipient id must be text")
    pieces = recipient_id.split(":")
    if len(pieces) != 3 or not all(pieces):
        raise M2CExecutorInputError("m2c recipient id must be platform:segment:function")
    platform, _segment, function_name = pieces
    if platform not in _SUPPORTED_PLATFORMS:
        raise M2CExecutorInputError("m2c recipient platform is unsupported")
    if re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", function_name) is None:
        raise M2CExecutorInputError("m2c recipient function is not a C identifier")
    return platform, function_name


def _safe_switches(value: Any) -> tuple[str, ...]:
    if not isinstance(value, (tuple, list)):
        raise M2CExecutorInputError("m2c switches must be a sequence")
    switches = tuple(value)
    if len(switches) > _MAX_SWITCHES:
        raise M2CExecutorInputError("m2c switch count exceeds its bound")
    seen: set[str] = set()
    for switch in switches:
        if not isinstance(switch, str) or switch not in _ALLOWED_SWITCHES:
            raise M2CExecutorInputError("m2c invocation contains an unapproved switch")
        if switch in seen:
            raise M2CExecutorInputError("m2c switches must not repeat")
        seen.add(switch)
        if any(char in switch for char in ("\x00", "/", "\\", "..")):
            raise M2CExecutorInputError("m2c switch contains path or NUL data")
    return switches


def _current_runtime_identity(platform: str) -> str:
    interpreter = "python3" if platform == _PLATFORM_WSL else "sys.executable"
    if platform == _PLATFORM_WSL:
        interpreter_identity = hash_canonical({"executable": "python3"})
    else:
        try:
            executable = str(Path(sys.executable).resolve(strict=False))
        except (OSError, RuntimeError):
            executable = sys.executable
        interpreter_identity = hash_bytes(executable.encode("utf-8"))
    return hash_canonical(
        {
            "protocol": M2C_RUNTIME_PROTOCOL,
            "platform": platform,
            "interpreter": interpreter,
            "interpreter_identity": interpreter_identity,
            "implementation": sys.implementation.name,
            "python_major": sys.version_info.major,
            "python_minor": sys.version_info.minor,
            "no_user_site": True,
            "no_bytecode": True,
        }
    )


def _pin_dict(pin: M2CRevisionPin) -> dict[str, Any]:
    return {**pin.identity_payload(), "pin_identity": pin.pin_identity}


_PIN_FIELDS = (
    "protocol",
    "revision",
    "source_artifact",
    "tool_artifact",
    "runner_identity",
    "available",
    "unavailable_reason",
    "pin_identity",
)


def _pin_from_dict(
    value: Any,
    *,
    archive: ContentAddressedArchive,
) -> M2CRevisionPin:
    data = _strict_mapping(value, _PIN_FIELDS, "m2c revision pin")
    if data["protocol"] != M2C_PIN_PROTOCOL:
        raise M2CExecutorInputError("m2c revision pin protocol differs")
    try:
        revision = M2CRevisionIdentity.from_dict(data["revision"])
        source = None if data["source_artifact"] is None else _artifact(data["source_artifact"], "pin source")
        tool = None if data["tool_artifact"] is None else _artifact(data["tool_artifact"], "pin tool")
        pin = M2CRevisionPin(
            revision=revision,
            source_artifact=source,
            tool_artifact=tool,
            runner_identity=data["runner_identity"],
            available=data["available"],
            unavailable_reason=data["unavailable_reason"],
        )
    except (M2CProviderError, TypeError, ValueError) as exc:
        raise M2CExecutorInputError("m2c revision pin is malformed") from exc
    if data["pin_identity"] != pin.pin_identity:
        raise M2CExecutorInputError("m2c revision pin identity changed")
    if pin.available:
        assert pin.source_artifact is not None and pin.tool_artifact is not None
        _archive_bytes(
            archive,
            pin.source_artifact,
            "pinned source artifact",
            prefix=_SOURCE_PREFIX,
            maximum=_MAX_TOOL_BYTES,
            reject_nul=False,
        )
        _archive_bytes(
            archive,
            pin.tool_artifact,
            "pinned tool artifact",
            prefix=_TOOL_PREFIX,
            maximum=_MAX_TOOL_BYTES,
            reject_nul=False,
        )
    return pin


@dataclass(frozen=True)
class M2CExecutorPreflight:
    status: str
    code: str
    platform: str
    revision_id: str
    pin_identity: str
    runner_identity: str
    target: Optional[str]
    target_map: Mapping[str, Optional[str]]
    runtime_identity: str
    detail: str = ""

    def __post_init__(self) -> None:
        if self.status not in {"ready", "unavailable", "refused", "inapplicable"}:
            raise M2CExecutorInputError("m2c preflight status is invalid")
        if not isinstance(self.code, str) or not self.code:
            raise M2CExecutorInputError("m2c preflight code is required")
        if self.platform not in _SUPPORTED_PLATFORMS | {_PLATFORM_POSIX, _PLATFORM_WSL}:
            raise M2CExecutorInputError("m2c preflight platform is invalid")
        if len(self.revision_id) != 40 or any(char not in "0123456789abcdef" for char in self.revision_id):
            raise M2CExecutorInputError("m2c preflight revision is invalid")
        _identity(self.pin_identity, "m2c preflight pin identity")
        _identity(self.runner_identity, "m2c preflight runner identity")
        _identity(self.runtime_identity, "m2c preflight runtime identity")
        if not isinstance(self.target_map, Mapping) or dict(self.target_map) != dict(M2C_TARGET_MAP):
            raise M2CExecutorInputError("m2c preflight target map is not exact")
        if not isinstance(self.detail, str):
            raise M2CExecutorInputError("m2c preflight detail must be text")

    @property
    def ready(self) -> bool:
        return self.status == "ready"

    def to_dict(self) -> dict[str, Any]:
        return {
            "protocol": M2C_PREFLIGHT_PROTOCOL,
            "status": self.status,
            "code": self.code,
            "platform": self.platform,
            "revision_id": self.revision_id,
            "pin_identity": self.pin_identity,
            "runner_identity": self.runner_identity,
            "target": self.target,
            "target_map": dict(self.target_map),
            "runtime_identity": self.runtime_identity,
            "detail": self.detail,
        }


@dataclass(frozen=True)
class M2CExecutionResult:
    status: str
    request_id: str
    invocation_id: str
    revision_id: str
    platform: str
    target: Optional[str]
    reason_code: str
    detail: str
    returncode: Optional[int] = None
    source_artifact: Optional[ArtifactRef] = None
    output_artifact: Optional[ArtifactRef] = None
    result_identity: str = ""

    def __post_init__(self) -> None:
        if self.status not in {"success", "unavailable", "refused", "timeout", "invalid", "inapplicable"}:
            raise M2CExecutorInputError("m2c result status is invalid")
        _identity(self.request_id, "m2c result request id")
        _identity(self.invocation_id, "m2c result invocation id")
        if len(self.revision_id) != 40 or any(char not in "0123456789abcdef" for char in self.revision_id):
            raise M2CExecutorInputError("m2c result revision is invalid")
        if self.platform not in _SUPPORTED_PLATFORMS:
            raise M2CExecutorInputError("m2c result platform is invalid")
        expected_target = _target_for(self.platform)
        if self.target != expected_target:
            raise M2CExecutorInputError("m2c result target map differs")
        if not isinstance(self.reason_code, str) or not self.reason_code:
            raise M2CExecutorInputError("m2c result reason code is required")
        if not isinstance(self.detail, str) or not self.detail:
            raise M2CExecutorInputError("m2c result detail is required")
        if self.returncode is not None and (
            isinstance(self.returncode, bool) or not isinstance(self.returncode, int)
        ):
            raise M2CExecutorInputError("m2c result return code is invalid")
        if self.source_artifact is not None:
            object.__setattr__(self, "source_artifact", _artifact(self.source_artifact, "m2c result source"))
        if self.output_artifact is not None:
            object.__setattr__(self, "output_artifact", _artifact(self.output_artifact, "m2c result output"))
        if self.status == "success" and self.source_artifact is None:
            raise M2CExecutorInputError("successful m2c result has no source artifact")
        if self.status != "success" and self.source_artifact is not None:
            raise M2CExecutorInputError("non-success m2c result has a source artifact")
        expected = hash_canonical(self.identity_payload())
        if self.result_identity and self.result_identity != expected:
            raise M2CExecutorInputError("m2c result identity changed")
        object.__setattr__(self, "result_identity", expected)

    def identity_payload(self) -> dict[str, Any]:
        return {
            "protocol": M2C_RESULT_PROTOCOL,
            "status": self.status,
            "request_id": self.request_id,
            "invocation_id": self.invocation_id,
            "revision_id": self.revision_id,
            "platform": self.platform,
            "target": self.target,
            "reason_code": self.reason_code,
            "detail": self.detail,
            "returncode": self.returncode,
            "source_artifact": _artifact_identity(self.source_artifact),
            "output_artifact": _artifact_identity(self.output_artifact),
        }

    def to_dict(self) -> dict[str, Any]:
        return {**self.identity_payload(), "result_identity": self.result_identity}

    @classmethod
    def from_dict(cls, value: Mapping[str, Any]) -> "M2CExecutionResult":
        fields = (
            "protocol",
            "status",
            "request_id",
            "invocation_id",
            "revision_id",
            "platform",
            "target",
            "reason_code",
            "detail",
            "returncode",
            "source_artifact",
            "output_artifact",
            "result_identity",
        )
        data = _strict_mapping(value, fields, "m2c result")
        if data["protocol"] != M2C_RESULT_PROTOCOL:
            raise M2CExecutorInputError("m2c result protocol differs")
        return cls(
            status=data["status"],
            request_id=data["request_id"],
            invocation_id=data["invocation_id"],
            revision_id=data["revision_id"],
            platform=data["platform"],
            target=data["target"],
            reason_code=data["reason_code"],
            detail=data["detail"],
            returncode=data["returncode"],
            source_artifact=(None if data["source_artifact"] is None else _artifact(data["source_artifact"], "m2c result source")),
            output_artifact=(None if data["output_artifact"] is None else _artifact(data["output_artifact"], "m2c result output")),
            result_identity=data["result_identity"],
        )


def _request_payload(
    *,
    executor_identity: str,
    invocation: M2CInvocation,
    platform: str,
    target: Optional[str],
    scratch_identity: str,
    scratch_path: str,
    limits: Mapping[str, Any],
) -> dict[str, Any]:
    return {
        "protocol": M2C_REQUEST_PROTOCOL,
        "executor_identity": executor_identity,
        "invocation": invocation.to_dict(),
        "platform": platform,
        "target": target,
        "scratch_identity": scratch_identity,
        "scratch_path": scratch_path,
        "limits": dict(limits),
    }


def _request_document(payload: Mapping[str, Any]) -> dict[str, Any]:
    return {"request_id": hash_canonical(payload), **dict(payload)}


def _json_no_duplicates(raw: bytes, label: str) -> Mapping[str, Any]:
    if len(raw) > _MAX_RECORD_BYTES:
        raise M2CExecutorInputError(f"{label} exceeds its immutable bound")
    duplicate = False

    def hook(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
        nonlocal duplicate
        result: dict[str, Any] = {}
        for key, value in pairs:
            if key in result:
                duplicate = True
            result[key] = value
        return result

    try:
        value = json.loads(raw.decode("utf-8"), object_pairs_hook=hook)
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise M2CExecutorInputError(f"{label} is not canonical JSON") from exc
    if duplicate or not isinstance(value, Mapping) or canonical_bytes(value) != raw:
        raise M2CExecutorInputError(f"{label} is not canonical or contains duplicate fields")
    return value


def _record_files(archive: ContentAddressedArchive, category: str, label: str) -> list[Mapping[str, Any]]:
    root = archive.run_root / "artifacts" / category
    try:
        if not root.exists():
            return []
        if root.is_symlink() or not root.is_dir():
            raise OSError("record category is not a regular directory")
        paths = sorted(root.iterdir(), key=lambda item: item.name)
    except OSError as exc:
        raise M2CExecutorInputError(f"{label} category cannot be inspected") from exc
    result: list[Mapping[str, Any]] = []
    seen: set[str] = set()
    for path in paths:
        if path.is_symlink() or not path.is_file() or path.suffix != ".json":
            raise M2CExecutorInputError(f"{label} category contains an unsafe file")
        if path.stem in seen:
            raise M2CExecutorInputError(f"{label} category contains duplicate records")
        seen.add(path.stem)
        try:
            raw = path.read_bytes()
        except OSError as exc:
            raise M2CExecutorInputError(f"{label} record cannot be read") from exc
        if path.stem != hash_bytes(raw).removeprefix("sha256:"):
            raise M2CExecutorInputError(f"{label} record filename identity changed")
        result.append(_json_no_duplicates(raw, f"{label} record"))
    return result


def _archive_relative(root: Path, relative: str, label: str) -> Path:
    try:
        validate_relative_path(relative, label)
        if "\\" in relative:
            raise ValueError("backslash")
        candidate = (root / Path(relative)).resolve(strict=False)
        candidate.relative_to(root.resolve(strict=False))
    except (OSError, RuntimeError, ValueError) as exc:
        raise M2CExecutorInputError(f"{label} escaped the run archive") from exc
    return candidate


def _ensure_directory(root: Path, relative: str, label: str) -> Path:
    target = _archive_relative(root, relative, label)
    try:
        relative_parts = target.relative_to(root.resolve(strict=False)).parts
        current = root.resolve(strict=False)
        current.mkdir(parents=True, exist_ok=True)
        for part in relative_parts:
            current = current / part
            if current.is_symlink():
                raise OSError("symlink")
            if current.exists():
                if not current.is_dir():
                    raise OSError("not a directory")
            else:
                current.mkdir()
        return current
    except OSError as exc:
        raise M2CExecutorUnavailable(f"{label} cannot be created") from exc


def _write_exact(root: Path, relative: str, data: bytes, label: str) -> Path:
    path = _archive_relative(root, relative, label)
    parent_rel = path.parent.relative_to(root.resolve(strict=False)).as_posix()
    if parent_rel != ".":
        _ensure_directory(root, parent_rel, f"{label} parent")
    try:
        if path.is_symlink():
            raise OSError("symlink")
        if path.exists():
            if not path.is_file() or path.read_bytes() != data:
                raise OSError("different bytes")
            return path
        flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL
        descriptor = os.open(str(path), flags, 0o644)
        with os.fdopen(descriptor, "wb") as stream:
            stream.write(data)
            stream.flush()
            os.fsync(stream.fileno())
    except FileExistsError:
        if path.is_symlink() or not path.is_file() or path.read_bytes() != data:
            raise M2CExecutorInputError(f"{label} raced with different bytes")
    except OSError as exc:
        if str(exc) == "different bytes":
            raise M2CExecutorInputError(f"{label} differs from the immutable scratch copy") from exc
        raise M2CExecutorUnavailable(f"{label} cannot be materialized") from exc
    return path


def _safe_member(name: str, label: str) -> str:
    if not isinstance(name, str) or not name or "\\" in name:
        raise M2CExecutorInvalidResponse(f"{label} has an unsafe archive member")
    parsed = PurePosixPath(name)
    if parsed.is_absolute() or any(part in {"", ".", ".."} for part in parsed.parts):
        raise M2CExecutorInvalidResponse(f"{label} has a traversal member")
    return parsed.as_posix()


def _materialize_tool(root: Path, data: bytes) -> Path:
    """Materialize a plain runner or a safe zip/tar runner package."""

    tool_root = _ensure_directory(root, "tool", "m2c tool directory")
    members: list[tuple[str, bytes]] = []
    stream = io.BytesIO(data)
    if zipfile.is_zipfile(stream):
        stream.seek(0)
        try:
            with zipfile.ZipFile(stream) as bundle:
                if len(bundle.infolist()) > _MAX_TOOL_FILES:
                    raise M2CExecutorInvalidResponse("m2c tool archive has too many files")
                for info in bundle.infolist():
                    name = _safe_member(info.filename, "m2c tool zip")
                    mode = (info.external_attr >> 16) & 0o170000
                    if info.is_dir() or mode == stat.S_IFDIR:
                        continue
                    if mode in {stat.S_IFLNK, stat.S_IFSOCK, stat.S_IFCHR, stat.S_IFBLK, stat.S_IFIFO}:
                        raise M2CExecutorInvalidResponse("m2c tool zip contains a special file")
                    item = bundle.read(info)
                    if len(item) > _MAX_TOOL_BYTES or sum(len(existing) for _, existing in members) + len(item) > _MAX_TOOL_BYTES:
                        raise M2CExecutorInvalidResponse("m2c tool archive exceeds its bound")
                    members.append((name, item))
        except (zipfile.BadZipFile, OSError) as exc:
            raise M2CExecutorInvalidResponse("m2c tool zip cannot be read") from exc
    else:
        stream.seek(0)
        try:
            with tarfile.open(fileobj=stream, mode="r:*") as bundle:
                infos = bundle.getmembers()
                if len(infos) > _MAX_TOOL_FILES:
                    raise M2CExecutorInvalidResponse("m2c tool archive has too many files")
                for info in infos:
                    name = _safe_member(info.name, "m2c tool tar")
                    if info.isdir():
                        continue
                    if info.issym() or info.islnk() or not info.isfile():
                        raise M2CExecutorInvalidResponse("m2c tool tar contains a special file")
                    extracted = bundle.extractfile(info)
                    if extracted is None:
                        raise M2CExecutorInvalidResponse("m2c tool tar member is unreadable")
                    item = extracted.read(_MAX_TOOL_BYTES + 1)
                    if len(item) > _MAX_TOOL_BYTES or sum(len(existing) for _, existing in members) + len(item) > _MAX_TOOL_BYTES:
                        raise M2CExecutorInvalidResponse("m2c tool archive exceeds its bound")
                    members.append((name, item))
        except (tarfile.TarError, OSError) as exc:
            # A normal Python file is not a tar archive.  It is the common
            # runner artifact shape and is handled below.
            if not members:
                members = [("m2c.py", data)]
            else:
                raise M2CExecutorInvalidResponse("m2c tool tar cannot be read") from exc
    if not members:
        raise M2CExecutorInvalidResponse("m2c tool package is empty")
    for relative, item in members:
        _write_exact(tool_root, relative, item, "m2c tool member")
    runners = [tool_root / relative for relative, _item in members if PurePosixPath(relative).name == "m2c.py"]
    if len(runners) != 1:
        raise M2CExecutorUnavailable("pinned m2c tool has no unique m2c.py runner", code="m2c_runner_missing")
    runner = runners[0]
    if runner.is_symlink() or not runner.is_file():
        raise M2CExecutorUnavailable("pinned m2c runner is not a regular file", code="m2c_runner_missing")
    return runner


def _parse_runner_output(output: bytes, maximum: int) -> str:
    if len(output) > maximum:
        raise M2CExecutorInvalidResponse("m2c runner output exceeds its bound")
    if not output or b"\x00" in output:
        raise M2CExecutorInvalidResponse("m2c runner output is empty or contains NUL bytes")
    try:
        source = output.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise M2CExecutorInvalidResponse("m2c runner output is not UTF-8") from exc
    if not source.strip():
        raise M2CExecutorInvalidResponse("m2c runner output is empty")
    return source


class M2CRevisionExecutor:
    """Concrete callback-free implementation of the m2c provider protocol."""

    def __init__(
        self,
        archive: ContentAddressedArchive,
        pin: M2CRevisionPin,
        *,
        archive_identity: str,
        manifest_identity: str,
        subset_identity: str,
        config_identity: str,
        tool_identity: str,
        timeout_seconds: float = 300.0,
        max_output_bytes: int = _MAX_OUTPUT_BYTES,
        max_source_bytes: int = _MAX_SOURCE_BYTES,
        max_context_bytes: int = _MAX_CONTEXT_BYTES,
        max_contexts: int = _MAX_CONTEXTS,
        max_switches: int = _MAX_SWITCHES,
    ) -> None:
        if not isinstance(archive, ContentAddressedArchive):
            raise M2CExecutorInputError("m2c executor archive must be content addressed")
        if not isinstance(pin, M2CRevisionPin):
            raise M2CExecutorInputError("m2c executor pin must be typed")
        for name, value in (
            ("archive_identity", archive_identity),
            ("manifest_identity", manifest_identity),
            ("subset_identity", subset_identity),
            ("config_identity", config_identity),
            ("tool_identity", tool_identity),
        ):
            _identity(value, "m2c " + name)
        if config_identity != pin.revision.config_identity:
            raise M2CExecutorInputError("m2c config identity differs from the pinned revision")
        if tool_identity != pin.revision.executable_identity:
            raise M2CExecutorInputError("m2c tool identity differs from the pinned executable")
        if isinstance(timeout_seconds, bool) or not isinstance(timeout_seconds, (int, float)):
            raise M2CExecutorInputError("m2c timeout must be numeric")
        timeout = float(timeout_seconds)
        if not math.isfinite(timeout) or timeout <= 0 or timeout > _MAX_TIMEOUT_SECONDS:
            raise M2CExecutorInputError("m2c timeout is outside its bound")
        for label, value, maximum in (
            ("max_output_bytes", max_output_bytes, _MAX_OUTPUT_BYTES),
            ("max_source_bytes", max_source_bytes, _MAX_SOURCE_BYTES),
            ("max_context_bytes", max_context_bytes, _MAX_CONTEXT_BYTES),
            ("max_contexts", max_contexts, _MAX_CONTEXTS),
            ("max_switches", max_switches, _MAX_SWITCHES),
        ):
            if isinstance(value, bool) or not isinstance(value, int) or value < 1 or value > maximum:
                raise M2CExecutorInputError(f"m2c {label} is outside its bound")
        self.archive = archive
        self.pin = pin
        self.archive_identity = archive_identity
        self.manifest_identity = manifest_identity
        self.subset_identity = subset_identity
        self.config_identity = config_identity
        self.tool_identity = tool_identity
        self.timeout_seconds = timeout
        self.max_output_bytes = max_output_bytes
        self.max_source_bytes = max_source_bytes
        self.max_context_bytes = max_context_bytes
        self.max_contexts = max_contexts
        self.max_switches = max_switches
        self._verify_pin()

    @property
    def platform(self) -> str:
        return _platform()

    @property
    def runtime_identity(self) -> str:
        return _current_runtime_identity(self.platform)

    @property
    def scratch_protocol(self) -> str:
        return M2C_SCRATCH_PROTOCOL

    @property
    def identity_payload(self) -> dict[str, Any]:
        return {
            "protocol": M2C_EXECUTOR_PROTOCOL,
            "module_identity": MODULE_IDENTITY,
            "pin_identity": self.pin.pin_identity,
            "revision_id": self.pin.revision_id,
            "provider_identity": self.pin.revision.provider_identity,
            "runner_identity": self.pin.runner_identity,
            "source_artifact": _artifact_identity(self.pin.source_artifact),
            "tool_artifact": _artifact_identity(self.pin.tool_artifact),
            "archive_identity": self.archive_identity,
            "manifest_identity": self.manifest_identity,
            "subset_identity": self.subset_identity,
            "config_identity": self.config_identity,
            "tool_identity": self.tool_identity,
            "target_map": dict(M2C_TARGET_MAP),
            "platform": self.platform,
            "runtime_identity": self.runtime_identity,
            "timeout_seconds": self.timeout_seconds,
            "max_output_bytes": self.max_output_bytes,
            "max_source_bytes": self.max_source_bytes,
            "max_context_bytes": self.max_context_bytes,
            "max_contexts": self.max_contexts,
            "max_switches": self.max_switches,
            "scratch_protocol": self.scratch_protocol,
        }

    @property
    def identity(self) -> str:
        return hash_canonical(self.identity_payload)

    @property
    def executor_identity(self) -> str:
        return self.identity

    def to_dict(self) -> dict[str, Any]:
        return {
            "protocol": M2C_EXECUTOR_PROTOCOL,
            "module_identity": MODULE_IDENTITY,
            "pin": _pin_dict(self.pin),
            "archive_identity": self.archive_identity,
            "manifest_identity": self.manifest_identity,
            "subset_identity": self.subset_identity,
            "config_identity": self.config_identity,
            "tool_identity": self.tool_identity,
            "target_map": dict(M2C_TARGET_MAP),
            "platform": self.platform,
            "runtime_identity": self.runtime_identity,
            "timeout_seconds": self.timeout_seconds,
            "max_output_bytes": self.max_output_bytes,
            "max_source_bytes": self.max_source_bytes,
            "max_context_bytes": self.max_context_bytes,
            "max_contexts": self.max_contexts,
            "max_switches": self.max_switches,
            "scratch_protocol": self.scratch_protocol,
            "executor_identity": self.identity,
        }

    @classmethod
    def from_dict(
        cls,
        value: Mapping[str, Any],
        *,
        archive: ContentAddressedArchive,
    ) -> "M2CRevisionExecutor":
        fields = (
            "protocol",
            "module_identity",
            "pin",
            "archive_identity",
            "manifest_identity",
            "subset_identity",
            "config_identity",
            "tool_identity",
            "target_map",
            "platform",
            "runtime_identity",
            "timeout_seconds",
            "max_output_bytes",
            "max_source_bytes",
            "max_context_bytes",
            "max_contexts",
            "max_switches",
            "scratch_protocol",
            "executor_identity",
        )
        data = _strict_mapping(value, fields, "m2c executor")
        if data["protocol"] != M2C_EXECUTOR_PROTOCOL:
            raise M2CExecutorInputError("m2c executor protocol differs")
        if data["module_identity"] != MODULE_IDENTITY:
            raise M2CExecutorInputError("m2c executor module identity differs")
        if not isinstance(data["target_map"], Mapping) or dict(data["target_map"]) != dict(M2C_TARGET_MAP):
            raise M2CExecutorInputError("m2c executor target map differs")
        if data["platform"] != _platform():
            raise M2CExecutorInputError("m2c executor platform differs")
        if data["scratch_protocol"] != M2C_SCRATCH_PROTOCOL:
            raise M2CExecutorInputError("m2c executor scratch protocol differs")
        if not isinstance(archive, ContentAddressedArchive):
            raise M2CExecutorInputError("m2c executor reconstruction needs an archive")
        pin = _pin_from_dict(data["pin"], archive=archive)
        executor = cls(
            archive,
            pin,
            archive_identity=data["archive_identity"],
            manifest_identity=data["manifest_identity"],
            subset_identity=data["subset_identity"],
            config_identity=data["config_identity"],
            tool_identity=data["tool_identity"],
            timeout_seconds=data["timeout_seconds"],
            max_output_bytes=data["max_output_bytes"],
            max_source_bytes=data["max_source_bytes"],
            max_context_bytes=data["max_context_bytes"],
            max_contexts=data["max_contexts"],
            max_switches=data["max_switches"],
        )
        if data["runtime_identity"] != executor.runtime_identity:
            raise M2CExecutorInputError("m2c executor runtime identity changed")
        if data["executor_identity"] != executor.identity:
            raise M2CExecutorInputError("m2c executor identity changed")
        return executor

    def resolve_revision(self, revision_id: str) -> M2CRevisionIdentity:
        if revision_id != self.pin.revision_id:
            raise M2CExecutorInputError("m2c revision is not the exact pinned revision")
        return self.pin.revision

    def _verify_pin(self) -> None:
        if not self.pin.available:
            detail = self.pin.unavailable_reason or "pinned m2c revision is unavailable"
            raise M2CExecutorUnavailable(detail, code="m2c_pinned_revision_unavailable")
        if self.pin.source_artifact is None or self.pin.tool_artifact is None:
            raise M2CExecutorUnavailable("pinned m2c source or tool is absent", code="m2c_pinned_artifact_unavailable")
        _archive_bytes(
            self.archive,
            self.pin.source_artifact,
            "pinned source artifact",
            prefix=_SOURCE_PREFIX,
            maximum=_MAX_TOOL_BYTES,
            reject_nul=False,
        )
        _archive_bytes(
            self.archive,
            self.pin.tool_artifact,
            "pinned tool artifact",
            prefix=_TOOL_PREFIX,
            maximum=_MAX_TOOL_BYTES,
            reject_nul=False,
        )

    def _limits(self) -> dict[str, Any]:
        return {
            "timeout_seconds": self.timeout_seconds,
            "max_output_bytes": self.max_output_bytes,
            "max_source_bytes": self.max_source_bytes,
            "max_context_bytes": self.max_context_bytes,
            "max_contexts": self.max_contexts,
            "max_switches": self.max_switches,
            "max_invocations": 1,
        }

    def _verify_invocation(
        self,
        invocation: M2CInvocation,
        assembly: bytes,
        contexts: tuple[bytes, ...],
    ) -> tuple[str, Optional[str], str, str, tuple[bytes, ...]]:
        if not isinstance(invocation, M2CInvocation):
            raise M2CExecutorInputError("m2c executor accepts only a typed invocation")
        platform, function_name = _recipient_parts(invocation.recipient_id)
        target = _target_for(platform)
        if invocation.revision_id != self.pin.revision_id:
            raise M2CExecutorInputError("m2c invocation revision differs from its pin")
        if invocation.tree_identity != self.pin.revision.tree_identity:
            raise M2CExecutorInputError("m2c invocation tree identity differs")
        if invocation.provider_identity != self.pin.revision.provider_identity:
            raise M2CExecutorInputError("m2c invocation provider identity differs")
        if invocation.tool_identity != self.tool_identity:
            raise M2CExecutorInputError("m2c invocation tool identity differs")
        if invocation.config_identity != self.config_identity:
            raise M2CExecutorInputError("m2c invocation config identity differs")
        if invocation.subset_identity != self.subset_identity:
            raise M2CExecutorInputError("m2c invocation subset identity differs")
        if invocation.archive_identity != self.archive_identity:
            raise M2CExecutorInputError("m2c invocation archive identity differs")
        switches = _safe_switches(invocation.switches)
        if len(switches) > self.max_switches:
            raise M2CExecutorInputError("m2c invocation switch count exceeds executor bound")
        if not isinstance(assembly, bytes) or len(assembly) > self.max_source_bytes or b"\x00" in assembly or not assembly:
            raise M2CExecutorInputError("m2c assembly is outside its immutable bound")
        contexts = tuple(contexts)
        if len(contexts) != len(invocation.context_artifacts) or len(contexts) > self.max_contexts:
            raise M2CExecutorInputError("m2c context cardinality differs from invocation")
        if len({item.content_hash for item in invocation.context_artifacts}) != len(invocation.context_artifacts):
            raise M2CExecutorInputError("m2c context artifacts repeat")
        _archive_bytes(
            self.archive,
            invocation.assembly_artifact,
            "m2c assembly artifact",
            prefix=_INPUT_PREFIX,
            maximum=self.max_source_bytes,
        )
        try:
            if self.archive.verify(invocation.assembly_artifact) != assembly:
                raise M2CExecutorInputError("m2c assembly differs from its archive artifact")
        except (ArchiveError, OSError, TypeError, ValueError) as exc:
            raise M2CExecutorInputError("m2c assembly artifact is missing or corrupt") from exc
        for reference, data in zip(invocation.context_artifacts, contexts):
            if not isinstance(data, bytes) or len(data) > self.max_context_bytes or b"\x00" in data or not data:
                raise M2CExecutorInputError("m2c context is outside its immutable bound")
            _archive_bytes(
                self.archive,
                reference,
                "m2c context artifact",
                prefix=_INPUT_PREFIX,
                maximum=self.max_context_bytes,
            )
            try:
                if self.archive.verify(reference) != data:
                    raise M2CExecutorInputError("m2c context differs from its archive artifact")
            except (ArchiveError, OSError, TypeError, ValueError) as exc:
                raise M2CExecutorInputError("m2c context artifact is missing or corrupt") from exc
        return platform, target, function_name, hash_canonical({"switches": list(switches)}), contexts

    def _scratch_identity(self, invocation: M2CInvocation) -> tuple[str, str]:
        identity = hash_canonical(
            {
                "protocol": M2C_SCRATCH_PROTOCOL,
                "executor_identity": self.identity,
                "invocation_id": invocation.invocation_id,
                "assembly_artifact": invocation.assembly_artifact.to_dict(),
                "context_artifacts": [item.to_dict() for item in invocation.context_artifacts],
                "platform": self.platform,
                "target_map": dict(M2C_TARGET_MAP),
            }
        )
        relative = _SCRATCH_ROOT + "/" + identity.removeprefix("sha256:")
        return identity, relative

    def _materialize(
        self,
        invocation: Optional[M2CInvocation],
        assembly: Optional[bytes],
        contexts: tuple[bytes, ...],
    ) -> tuple[Path, Path, Optional[Path], Optional[str]]:
        if invocation is None:
            scratch_identity = hash_canonical(
                {
                    "protocol": M2C_SCRATCH_PROTOCOL,
                    "executor_identity": self.identity,
                    "purpose": "preflight",
                }
            )
            scratch_relative = _SCRATCH_ROOT + "/preflight-" + scratch_identity.removeprefix("sha256:")
        else:
            scratch_identity, scratch_relative = self._scratch_identity(invocation)
        del scratch_identity
        scratch = _ensure_directory(self.archive.run_root, scratch_relative, "m2c scratch")
        source = _archive_bytes(
            self.archive,
            self.pin.source_artifact,
            "pinned source artifact",
            prefix=_SOURCE_PREFIX,
            maximum=_MAX_TOOL_BYTES,
            reject_nul=False,
        )
        tool = _archive_bytes(
            self.archive,
            self.pin.tool_artifact,
            "pinned tool artifact",
            prefix=_TOOL_PREFIX,
            maximum=_MAX_TOOL_BYTES,
            reject_nul=False,
        )
        _write_exact(scratch, "pinned-source.bin", source, "pinned source scratch")
        runner = _materialize_tool(scratch, tool)
        if invocation is None:
            return scratch, runner, None, None
        assert assembly is not None
        _write_exact(scratch, "input.s", assembly, "m2c assembly scratch")
        for index, context in enumerate(contexts):
            _write_exact(scratch, f"context-{index}.c", context, "m2c context scratch")
        return scratch, runner, scratch / "input.s", _recipient_parts(invocation.recipient_id)[1]

    @staticmethod
    def _minimal_env() -> dict[str, str]:
        return {
            "PATH": os.environ.get("PATH", ""),
            "LANG": "C",
            "LC_ALL": "C",
            "PYTHONHASHSEED": "0",
            "PYTHONNOUSERSITE": "1",
            "PYTHONDONTWRITEBYTECODE": "1",
            "PYTHONUNBUFFERED": "1",
        }

    def _wsl_executable(self) -> str:
        if not _is_windows_host():
            raise M2CExecutorInputError("WSL executable requested on a non-Windows host")
        executable = shutil.which("wsl.exe")
        if executable is None:
            raise M2CExecutorUnavailable("Windows host has no usable wsl.exe", code="m2c_wsl_unavailable")
        return executable

    def _wsl_path(self, path: Path) -> str:
        wsl = self._wsl_executable()
        try:
            result = subprocess.run(
                [wsl, "--exec", "wslpath", "-a", "-u", str(path)],
                capture_output=True,
                text=True,
                encoding="utf-8",
                errors="strict",
                timeout=_MAX_PREFLIGHT_TIMEOUT_SECONDS,
                check=False,
                shell=False,
                env=self._minimal_env(),
            )
        except (OSError, subprocess.SubprocessError) as exc:
            raise M2CExecutorUnavailable("Windows WSL path translation failed", code="m2c_wsl_path_unavailable") from exc
        translated = (result.stdout or "").strip()
        if result.returncode != 0 or not translated.startswith("/") or "\n" in translated or "\x00" in translated:
            raise M2CExecutorUnavailable("Windows WSL returned an unsafe path", code="m2c_wsl_path_unavailable")
        return translated

    def _runner_argv(
        self,
        scratch: Path,
        runner: Path,
        invocation: Optional[M2CInvocation],
        *,
        target: Optional[str] = None,
        function_name: Optional[str] = None,
        help_only: bool = False,
    ) -> tuple[list[str], Optional[str]]:
        if _is_windows_host():
            wsl = self._wsl_executable()
            wsl_root = self._wsl_path(runner.parent)
            wsl_runner = self._wsl_path(runner)
            command = [wsl, "--cd", wsl_root, "--exec", "python3", "-B", "-u", wsl_runner]
            if help_only:
                command.append("--help")
                return command, None
            assert invocation is not None and target is not None and function_name is not None
            command.extend(["--no-cache", "--target", target])
            command.extend(invocation.switches)
            for index in range(len(invocation.context_artifacts)):
                command.extend(["--context", self._wsl_path(scratch / f"context-{index}.c")])
            command.extend(["-f", function_name, self._wsl_path(scratch / "input.s")])
            return command, None
        command = [sys.executable, "-B", "-u", str(runner)]
        if help_only:
            command.append("--help")
            return command, str(runner.parent)
        assert invocation is not None and target is not None and function_name is not None
        command.extend(["--no-cache", "--target", target])
        command.extend(invocation.switches)
        for index in range(len(invocation.context_artifacts)):
            command.extend(["--context", str(scratch / f"context-{index}.c")])
        command.extend(["-f", function_name, str(scratch / "input.s")])
        return command, str(runner.parent)

    def _terminate(self, process: Any) -> None:
        try:
            process.terminate()
            process.wait(timeout=5)
        except (OSError, subprocess.SubprocessError, AttributeError):
            try:
                process.kill()
                process.wait(timeout=5)
            except (OSError, subprocess.SubprocessError, AttributeError):
                pass

    def _run_process(self, command: Sequence[str], cwd: Optional[str]) -> bytes:
        try:
            process = subprocess.Popen(
                list(command),
                cwd=cwd,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                shell=False,
                env=self._minimal_env(),
                start_new_session=not _is_windows_host(),
            )
            output, _ = process.communicate(timeout=self.timeout_seconds)
        except subprocess.TimeoutExpired as exc:
            self._terminate(locals().get("process"))
            raise M2CExecutorTimeout("m2c runner exceeded its timeout") from exc
        except (OSError, subprocess.SubprocessError) as exc:
            raise M2CExecutorUnavailable("m2c runner could not be started", code="m2c_runner_unavailable") from exc
        if isinstance(output, str):
            output = output.encode("utf-8")
        if not isinstance(output, bytes):
            raise M2CExecutorInvalidResponse("m2c runner returned non-byte output")
        if len(output) > self.max_output_bytes:
            raise M2CExecutorInvalidResponse("m2c runner output exceeds its bound")
        returncode = getattr(process, "returncode", None)
        if returncode != 0:
            detail = " ".join(output.decode("utf-8", "replace").split())[-256:]
            raise M2CExecutorRefused(
                detail or "m2c runner returned a nonzero status",
                code="m2c_runner_refused",
            )
        return output

    def _probe_runner(self, scratch: Path, runner: Path) -> None:
        command, cwd = self._runner_argv(scratch, runner, None, help_only=True)
        try:
            result = subprocess.run(
                command,
                cwd=cwd,
                capture_output=True,
                text=True,
                encoding="utf-8",
                errors="replace",
                timeout=min(self.timeout_seconds, _MAX_PREFLIGHT_TIMEOUT_SECONDS),
                check=False,
                shell=False,
                env=self._minimal_env(),
            )
        except subprocess.TimeoutExpired as exc:
            raise M2CExecutorTimeout("m2c preflight exceeded its timeout") from exc
        except (OSError, subprocess.SubprocessError) as exc:
            raise M2CExecutorUnavailable("m2c preflight could not start", code="m2c_runner_preflight_failed") from exc
        output = ((result.stdout or "") + "\n" + (result.stderr or "")).lower()
        if result.returncode != 0 or "m2c" not in output:
            raise M2CExecutorUnavailable("pinned m2c runner failed its real preflight", code="m2c_runner_preflight_failed")

    def preflight(self) -> M2CExecutorPreflight:
        """Run the fixed runner's help probe over verified current-pin bytes."""

        try:
            self._verify_pin()
            scratch, runner, _input, _function = self._materialize(None, None, ())
            self._probe_runner(scratch, runner)
        except M2CExecutorInapplicable as exc:
            return M2CExecutorPreflight(
                "inapplicable", exc.code, self.platform, self.pin.revision_id, self.pin.pin_identity,
                self.pin.runner_identity, None, dict(M2C_TARGET_MAP), self.runtime_identity, str(exc)
            )
        except M2CExecutorError as exc:
            return M2CExecutorPreflight(
                exc.status if exc.status in {"unavailable", "refused"} else "unavailable",
                exc.code, self.platform, self.pin.revision_id, self.pin.pin_identity,
                self.pin.runner_identity, None, dict(M2C_TARGET_MAP), self.runtime_identity, str(exc)
            )
        return M2CExecutorPreflight(
            "ready", "m2c_runner_ready", self.platform, self.pin.revision_id, self.pin.pin_identity,
            self.pin.runner_identity, None, dict(M2C_TARGET_MAP), self.runtime_identity,
            "pinned m2c runner passed its archive-backed help preflight",
        )

    def _find_replay(
        self,
        request: Mapping[str, Any],
        invocation: M2CInvocation,
    ) -> Optional[M2CExecutionResult]:
        request_data = _strict_mapping(
            request,
            (
                "request_id", "protocol", "executor_identity", "invocation", "platform", "target",
                "scratch_identity", "scratch_path", "limits",
            ),
            "m2c request",
        )
        if request_data["protocol"] != M2C_REQUEST_PROTOCOL:
            raise M2CExecutorInputError("m2c request protocol differs")
        expected = hash_canonical({key: request_data[key] for key in request_data if key != "request_id"})
        if request_data["request_id"] != expected:
            raise M2CExecutorInputError("m2c request identity changed")
        try:
            saved_invocation = M2CInvocation.from_dict(request_data["invocation"])
        except (M2CProviderError, TypeError, ValueError) as exc:
            raise M2CExecutorInputError("m2c request invocation is malformed") from exc
        if saved_invocation != invocation:
            raise M2CExecutorInputError("m2c request invocation differs from the current request")
        if request_data["executor_identity"] != self.identity:
            raise M2CExecutorInputError("m2c request executor identity differs")
        results = _record_files(self.archive, _RESULT_CATEGORY, "m2c result")
        matching: list[M2CExecutionResult] = []
        orphan = False
        for raw in results:
            try:
                result = M2CExecutionResult.from_dict(raw)
            except M2CExecutorError:
                raise
            if result.request_id == request_data["request_id"]:
                matching.append(result)
            elif result.invocation_id == invocation.invocation_id:
                orphan = True
        if len(matching) > 1:
            raise M2CExecutorInputError("m2c request has duplicate terminal results")
        if orphan and not matching:
            raise M2CExecutorInputError("m2c invocation has an orphaned terminal result")
        if matching:
            result = matching[0]
            if (
                result.invocation_id != invocation.invocation_id
                or result.revision_id != self.pin.revision_id
                or result.platform != request_data["platform"]
                or result.target != request_data["target"]
            ):
                raise M2CExecutorInputError("m2c terminal result differs from its request")
            self._verify_result_artifacts(result)
            return result
        return None

    def _find_request(self, request_id: str, invocation: M2CInvocation) -> tuple[Optional[Mapping[str, Any]], Optional[M2CExecutionResult]]:
        requests = _record_files(self.archive, _REQUEST_CATEGORY, "m2c request")
        matching: list[Mapping[str, Any]] = []
        for request in requests:
            data = _strict_mapping(
                request,
                (
                    "request_id", "protocol", "executor_identity", "invocation", "platform", "target",
                    "scratch_identity", "scratch_path", "limits",
                ),
                "m2c request",
            )
            expected = hash_canonical({key: data[key] for key in data if key != "request_id"})
            if data["request_id"] != expected:
                raise M2CExecutorInputError("m2c request identity changed")
            if data["executor_identity"] == self.identity and data["request_id"] == request_id:
                matching.append(data)
        if len(matching) > 1:
            raise M2CExecutorInputError("m2c request has duplicate records")
        if not matching:
            for raw in _record_files(self.archive, _RESULT_CATEGORY, "m2c result"):
                result = M2CExecutionResult.from_dict(raw)
                if result.invocation_id == invocation.invocation_id:
                    raise M2CExecutorInputError("m2c invocation has a result without its durable request")
            return None, None
        saved = matching[0]
        result = self._find_replay(saved, invocation)
        return saved, result

    def _verify_result_artifacts(self, result: M2CExecutionResult) -> None:
        if result.source_artifact is not None:
            _archive_bytes(
                self.archive,
                result.source_artifact,
                "m2c result source artifact",
                prefix=_DRAFT_PREFIX,
                maximum=self.max_source_bytes,
            )
        if result.output_artifact is not None:
            _archive_bytes(
                self.archive,
                result.output_artifact,
                "m2c result output artifact",
                prefix=_OUTPUT_PREFIX,
                maximum=self.max_output_bytes,
                allow_empty=True,
            )

    def _persist_result(
        self,
        request_id: str,
        invocation: M2CInvocation,
        platform: str,
        target: Optional[str],
        error: Optional[M2CExecutorError] = None,
        *,
        source: Optional[str] = None,
        output: Optional[bytes] = None,
        returncode: Optional[int] = None,
    ) -> M2CExecutionResult:
        source_ref: Optional[ArtifactRef] = None
        output_ref: Optional[ArtifactRef] = None
        if source is not None:
            source_ref = self.archive.put_bytes(
                source.encode("utf-8"),
                category="m2c-drafts",
                suffix=".c",
                media_type="text/x-c",
            )
        if output is not None and len(output) <= self.max_output_bytes:
            output_ref = self.archive.put_bytes(
                output,
                category="m2c-executor-output",
                suffix=".txt",
                media_type="text/plain",
            )
        if error is None:
            status = "success"
            reason_code = "m2c_completed"
            detail = "pinned m2c runner completed within immutable bounds"
        else:
            status = error.status
            reason_code = error.code
            detail = str(error)
        result = M2CExecutionResult(
            status=status,
            request_id=request_id,
            invocation_id=invocation.invocation_id,
            revision_id=self.pin.revision_id,
            platform=platform,
            target=target,
            reason_code=reason_code,
            detail=detail,
            returncode=returncode,
            source_artifact=source_ref,
            output_artifact=output_ref,
        )
        document = result.to_dict()
        stored = self.archive.put_json(document, category=_RESULT_CATEGORY)
        if self.archive.verify(stored) != canonical_bytes(document):
            raise M2CExecutorUnavailable("m2c result archive verification failed", code="m2c_result_archive_failed")
        return result

    def execute(
        self,
        invocation: M2CInvocation,
        *,
        assembly: bytes,
        contexts: tuple[bytes, ...],
    ) -> M2CExecutionResult:
        """Execute exactly once, or return a durable terminal replay."""

        platform, target, function_name, _switch_identity, contexts = self._verify_invocation(
            invocation, assembly, tuple(contexts)
        )
        scratch_identity, scratch_path = self._scratch_identity(invocation)
        request_payload = _request_payload(
            executor_identity=self.identity,
            invocation=invocation,
            platform=platform,
            target=target,
            scratch_identity=scratch_identity,
            scratch_path=scratch_path,
            limits=self._limits(),
        )
        request_document = _request_document(request_payload)
        request_id = request_document["request_id"]
        saved, replay = self._find_request(request_id, invocation)
        if saved is not None:
            if replay is not None:
                return replay
            raise M2CExecutorPending("m2c request is durable but has no terminal result")
        try:
            request_ref = self.archive.put_json(request_document, category=_REQUEST_CATEGORY)
            if self.archive.verify(request_ref) != canonical_bytes(request_document):
                raise M2CExecutorUnavailable("m2c request archive verification failed", code="m2c_request_archive_failed")
        except M2CExecutorError:
            raise
        except Exception as exc:
            raise M2CExecutorUnavailable("m2c request could not be durably archived", code="m2c_request_archive_failed") from exc
        if target is None:
            result = self._persist_result(
                request_id,
                invocation,
                platform,
                target,
                M2CExecutorInapplicable(
                    "pinned m2c has no Saturn/SH backend", code="m2c_target_inapplicable"
                ),
            )
            return result
        output: Optional[bytes] = None
        execution_error: Optional[M2CExecutorError] = None
        source: Optional[str] = None
        try:
            scratch, runner, _input, _function = self._materialize(invocation, assembly, contexts)
            command, cwd = self._runner_argv(
                scratch,
                runner,
                invocation,
                target=target,
                function_name=function_name,
            )
            output = self._run_process(command, cwd)
            source = _parse_runner_output(output, self.max_output_bytes)
        except M2CExecutorError as exc:
            execution_error = exc
        except Exception:
            execution_error = M2CExecutorInvalidResponse("m2c runner failed inside its trusted boundary")
        return self._persist_result(
            request_id,
            invocation,
            platform,
            target,
            execution_error,
            source=source,
            output=output,
            returncode=(0 if execution_error is None else None),
        )

    __call__ = execute
    invoke = execute

    def generate_draft(
        self,
        invocation: M2CInvocation,
        *,
        assembly: bytes,
        contexts: tuple[bytes, ...],
    ) -> M2CDraftPayload:
        result = self.execute(invocation, assembly=assembly, contexts=contexts)
        if result.status != "success":
            error_type: type[M2CExecutorError]
            error_type = {
                "unavailable": M2CExecutorUnavailable,
                "refused": M2CExecutorRefused,
                "timeout": M2CExecutorTimeout,
                "invalid": M2CExecutorInvalidResponse,
                "inapplicable": M2CExecutorInapplicable,
            }.get(result.status, M2CExecutorError)
            raise error_type(result.detail, code=result.reason_code)
        assert result.source_artifact is not None
        return M2CDraftPayload(
            invocation_id=invocation.invocation_id,
            revision_id=self.pin.revision_id,
            source_artifact=result.source_artifact,
        )


TrustedM2CRevisionExecutor = M2CRevisionExecutor
M2CExecutor = M2CRevisionExecutor


def build_m2c_revision_executor(
    archive: ContentAddressedArchive,
    pin: M2CRevisionPin,
    *,
    archive_identity: str,
    manifest_identity: str,
    subset_identity: str,
    config_identity: str,
    tool_identity: str,
    timeout_seconds: float = 300.0,
    max_output_bytes: int = _MAX_OUTPUT_BYTES,
    max_source_bytes: int = _MAX_SOURCE_BYTES,
    max_context_bytes: int = _MAX_CONTEXT_BYTES,
    max_contexts: int = _MAX_CONTEXTS,
    max_switches: int = _MAX_SWITCHES,
) -> M2CRevisionExecutor:
    return M2CRevisionExecutor(
        archive,
        pin,
        archive_identity=archive_identity,
        manifest_identity=manifest_identity,
        subset_identity=subset_identity,
        config_identity=config_identity,
        tool_identity=tool_identity,
        timeout_seconds=timeout_seconds,
        max_output_bytes=max_output_bytes,
        max_source_bytes=max_source_bytes,
        max_context_bytes=max_context_bytes,
        max_contexts=max_contexts,
        max_switches=max_switches,
    )


make_m2c_revision_executor = build_m2c_revision_executor


def verify_m2c_revision_pin(pin: M2CRevisionPin, *, archive: ContentAddressedArchive) -> None:
    """Read-only current-pin artifact preflight for callers without a run binding."""

    if not isinstance(pin, M2CRevisionPin):
        raise M2CExecutorInputError("m2c revision pin must be typed")
    if not pin.available or pin.source_artifact is None or pin.tool_artifact is None:
        raise M2CExecutorUnavailable("pinned m2c source or tool is unavailable", code="m2c_pinned_artifact_unavailable")
    _archive_bytes(
        archive,
        pin.source_artifact,
        "pinned source artifact",
        prefix=_SOURCE_PREFIX,
        maximum=_MAX_TOOL_BYTES,
        reject_nul=False,
    )
    _archive_bytes(
        archive,
        pin.tool_artifact,
        "pinned tool artifact",
        prefix=_TOOL_PREFIX,
        maximum=_MAX_TOOL_BYTES,
        reject_nul=False,
    )


__all__ = [
    "CURRENT_M2C_REVISION",
    "M2C_EXECUTOR_PROTOCOL",
    "M2C_RUNTIME_PROTOCOL",
    "M2C_PREFLIGHT_PROTOCOL",
    "M2C_REQUEST_PROTOCOL",
    "M2C_RESULT_PROTOCOL",
    "M2C_SCRATCH_PROTOCOL",
    "M2C_TARGET_MAP",
    "M2CExecutor",
    "M2CExecutorError",
    "M2CExecutorInputError",
    "M2CExecutorUnavailable",
    "M2CExecutorRefused",
    "M2CExecutorTimeout",
    "M2CExecutorInvalidResponse",
    "M2CExecutorInapplicable",
    "M2CExecutorPending",
    "M2CExecutorPreflight",
    "M2CExecutionResult",
    "M2CRevisionExecutor",
    "TrustedM2CRevisionExecutor",
    "build_m2c_revision_executor",
    "make_m2c_revision_executor",
    "verify_m2c_revision_pin",
]
