#!/usr/bin/env python3
"""Generate the README status tables instead of maintaining them by hand.

WHY THIS EXISTS
    The 2026-08-10 audit flagged README drift as its only red item, and it was
    right: the block said "Measured 2026-08-09" and claimed 198 matched, 184
    todo, 50 escalated, 31 deferred while the live queue held 203 / 126 / 102 /
    33. The provenance table was staler still -- it predates `transplant`
    existing as a source at all, so eight transplanted matches were sitting in
    its 21% `unknown` bucket.

    Every one of those numbers already had a generator. Nobody was running
    them. That is the whole defect, and hand-editing the numbers again would
    just restart the clock.

WHAT IT REGENERATES
    Four detailed README blocks, including the exact active work scope, plus
    one compact status block in each living operational document. ROADMAP.md
    shares the generated work-scope table. HTML comment markers keep surrounding prose
    untouched and make re-running idempotent:

        <!-- STATUS:BEGIN -->      queue / oracle / completion / inventory
        <!-- PROVENANCE:BEGIN -->  the how-were-these-matched table
        <!-- COMPLETION:BEGIN -->  detailed per-binary completion
        <!-- WORK-SCOPE:BEGIN -->  exact configs, stubs and queue lanes

COMPLETION AUTHORITY
    The completion headline is delegated to `automation/progress_table.py`,
    which reads the linker maps and live source ownership. This module does not
    reimplement that calculation. The detailed per-binary table remains in the
    README's Completion section: `progress_table.markdown()` owns its rendering,
    while this module's `--write` owns marker-delimited replacement.

    THE ORACLE IS READ, NEVER RUN. Building takes minutes and needs the lock.
    This hashes whatever artifacts are on disk and reports the result with the
    caveat that it reflects the last build, not this instant. If there are no
    artifacts it says so instead of printing a comforting number.

STRICTLY READ-ONLY unless --write is passed.

Usage:
    python3 automation/readme_status.py            # print, change nothing
    python3 automation/readme_status.py --write    # update all living docs
    python3 automation/readme_status.py --drift    # fail on stale docs
    python3 automation/readme_status.py --self-test
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import time
from pathlib import Path

import run_selftests as selftest_runner
from queue_coverage import (
    REQUIRED_US_ARTIFACTS,
    REQUIRED_US_CONFIGS,
    collect as queue_coverage_collect,
    required_scope_gaps,
    us_src_dirs,
)

REPO = Path(__file__).resolve().parent.parent
AUTO = REPO / "automation"
README = REPO / "README.md"
PYTHON = str(REPO / ".venv" / "bin" / "python")
if not Path(PYTHON).exists():                                # pragma: no cover
    PYTHON = sys.executable

STATUS_BEGIN = "<!-- STATUS:BEGIN -->"
STATUS_END = "<!-- STATUS:END -->"
PROV_BEGIN = "<!-- PROVENANCE:BEGIN -->"
PROV_END = "<!-- PROVENANCE:END -->"
COMPLETION_BEGIN = "<!-- COMPLETION:BEGIN -->"
COMPLETION_END = "<!-- COMPLETION:END -->"
LIVE_STATUS_BEGIN = "<!-- LIVE-STATUS:BEGIN -->"
LIVE_STATUS_END = "<!-- LIVE-STATUS:END -->"
WORK_SCOPE_BEGIN = "<!-- WORK-SCOPE:BEGIN -->"
WORK_SCOPE_END = "<!-- WORK-SCOPE:END -->"

# Living documents that carry a compact view of the same data used by the
# README. Historical audits and archived plans are deliberately excluded.
LIVE_STATUS_DOCS = (
    "ROADMAP.md",
    "ORCHESTRATOR.md",
    "automation/README.md",
    "docs/TOOLING.md",
    "docs/CONNECTORS.md",
    "docs/HARNESS-ARCHITECTURE.md",
)
WORK_SCOPE_DOCS = ("README.md", "ROADMAP.md")

GENERATED = ("*Generated by `automation/readme_status.py`. Do not edit by "
             "hand; run the tool.*")


def _run(args: list[str], timeout: int = 300) -> str:
    try:
        r = subprocess.run(args, cwd=str(REPO), capture_output=True,
                           text=True, timeout=timeout)
        return r.stdout
    except (OSError, subprocess.SubprocessError):
        return ""


def queue_counts() -> dict[str, int]:
    """Through scheduler.py, never off the queue file.

    SOTN_QUEUE resolves per environment, so a direct read answers about a
    different file. deferred_triage documents an incident where a snapshot
    reported 33 matched against a live 134.
    """
    out = _run([PYTHON, str(AUTO / "scheduler.py"), "stats"])
    counts: dict[str, int] = {}
    for line in out.splitlines():
        # `total 470` is space-separated; every other row is `   todo: 126`.
        # The first version required whitespace and so matched ONLY `total`,
        # and the generated table shipped as "470 records:" with nothing after
        # the colon. An empty rendering is the one outcome a status generator
        # must not produce quietly.
        m = re.match(r"\s*(\w+)[:\s]\s*(\d+)\s*$", line)
        if m:
            counts[m.group(1)] = int(m.group(2))
    return counts


def oracle() -> tuple[int, int, bool]:
    """(matched, expected, artifacts_present) from the LAST build. Read-only."""
    sys.path.insert(0, str(AUTO))
    try:
        from permuter_supervisor import verify_checksums   # type: ignore
    except Exception:                                       # noqa: BLE001
        return (0, 0, False)
    try:
        ok, detail = verify_checksums("us")
    except Exception:                                       # noqa: BLE001
        return (0, 0, False)
    m = re.search(r"(\d+)\s*/\s*(\d+)", detail or "")
    if not m:
        return (0, 0, False)
    return (int(m.group(1)), int(m.group(2)), True)


def stub_counts(us_only: bool = True) -> tuple[int, dict[str, int]]:
    """INCLUDE_ASM stubs left in src/, by top-level area.

    us_only=False is used ONLY to state, in the README, how much bigger the
    number gets when the non-us trees are included. Quoting the difference is
    what stops the next reader assuming the figure shrank.
    """
    rx = re.compile(r"^\s*INCLUDE_ASM\(", re.M)
    compiled_dirs = us_src_dirs() if us_only else set()
    per: dict[str, int] = {}
    total = 0
    for p in (REPO / "src").rglob("*.c"):
        rel = p.relative_to(REPO).as_posix()
        if compiled_dirs and not any(
                rel.startswith(d.rstrip("/") + "/") for d in compiled_dirs):
            continue
        try:
            n = len(rx.findall(p.read_text(errors="ignore")))
        except OSError:
            continue
        if not n:
            continue
        total += n
        area = p.relative_to(REPO / "src").parts[0]
        per[area] = per.get(area, 0) + n
    return total, per


def inventory() -> dict[str, int]:
    """Counts that are DISCOVERED, not written down.

    Every one of these was a hand-maintained number somewhere at some point,
    and every hand-maintained number in this repo has drifted: fleet_start's
    help omitted `zen` for weeks, the old run_analysis docstring listed seven of
    forty-five scripts, match_provenance enumerated two `_from_` suffixes out
    of five. Count them.
    """
    mods = [p for p in AUTO.rglob("*.py") if ".venv" not in p.parts]
    # Use the runner's actual discovery functions. A second approximation here
    # counted run_selftests.py itself and recursively scanned modules the runner
    # never invokes, so the generated README claimed 32 while the gate ran 31.
    suites = selftest_runner.suites()
    selftests = len(selftest_runner.selftest_modules())
    tools = 0
    for name in ("sotn_cmd_mcp.py", "sotn_local_mcp.py"):
        f = AUTO / "mcp" / name
        if f.is_file():
            tools += len(re.findall(r"@mcp\.tool\(\)",
                                    f.read_text(errors="ignore")))
    diagnostics = 0
    try:
        sys.path.insert(0, str(AUTO / "mcp"))
        import commands_client as cc                        # type: ignore
        diagnostics = len(cc.AUTOMATION_SCRIPTS)
    except Exception:                                       # noqa: BLE001
        pass
    return {"modules": len(mods), "suites": len(suites),
            "selftests": selftests, "tools": tools,
            "diagnostics": diagnostics}


_COMPLETION: tuple[float, int, int, int] | None = None
_COMPLETION_ROWS: list | None = None


def completion_rows() -> list:
    """Return progress_table's rows once for both README views."""
    global _COMPLETION_ROWS
    if _COMPLETION_ROWS is None:
        sys.path.insert(0, str(AUTO))
        import progress_table as pt                         # type: ignore
        _COMPLETION_ROWS = pt.gather("us")
    return _COMPLETION_ROWS


def completion() -> tuple[float, int, int, int]:
    """(code percent, functions done, total, built binaries).

    progress_table owns the classification. Keeping this as a delegation is
    what prevents the headline and detailed table from becoming two metrics
    that merely happen to share a label.
    """
    global _COMPLETION
    if _COMPLETION is None:
        sys.path.insert(0, str(AUTO))
        import progress_table as pt                         # type: ignore
        rows = completion_rows()
        cp, _fp, fd, ft = pt.totals(rows)
        _COMPLETION = (cp, fd, ft, len(rows))
    return _COMPLETION


_RAW: list[dict] | None = None


def raw_rows() -> list[dict]:
    """match_provenance's per-record attribution, computed once and shared.

    THE TABLE AND THE PROSE MUST COME FROM ONE READ. They did not: the table
    said 28% unknown while the paragraph under it said 21%, and that paragraph
    also broke the figure down as "36 overwritten, 51 never noted" against a
    total that had moved twice. Two hand-synchronised views of one dataset
    drift the moment either is regenerated alone.
    """
    global _RAW
    if _RAW is None:
        sys.path.insert(0, str(AUTO))
        import match_provenance as mp                       # type: ignore
        try:
            recs = mp.load_queue()                          # type: ignore
            _RAW = mp.analyse(recs, use_git=False, jobs=1,  # type: ignore
                              progress=False)
        except Exception as e:                              # noqa: BLE001
            raise RuntimeError(
                f"match_provenance failed: {type(e).__name__}: {e}")
    return _RAW


def provenance_rows() -> list[tuple[str, int, str]]:
    """(source, count, blurb) from match_provenance, in its own precedence."""
    sys.path.insert(0, str(AUTO))
    import match_provenance as mp                           # type: ignore
    rows = raw_rows()
    from collections import Counter
    prim = Counter(r["primary"] for r in rows)
    # KEEP THIS IN STEP WITH match_provenance._PRECEDENCE. A source with no
    # entry here renders as an empty cell, which is exactly what happened when
    # `upstream-harvest` was added on 2026-08-16: the table printed a count of
    # 25 against a blank explanation, so the largest single category in it said
    # nothing about itself. The loop below iterates _PRECEDENCE, so a new
    # source appears in the table whether or not anyone described it.
    blurb = {
        "upstream-harvest": "upstream had already decompiled it; copied and "
                            "verified here, **not** produced by this fork",
        "shim-segment": "shared header plus splat segment work",
        "shim-header": "body copied from a shared header",
        "transplant": "transplant.py moved a twin body in mechanically",
        "twin-port": "ported from a sibling overlay or RIC, by hand",
        "permuter": "decomp-permuter search reached 0",
        "model-fleet": "an OpenCode or llama worker wrote it",
        "claude-manual": "written or repaired by hand",
        "unknown": "evidence insufficient; **not** a guess",
    }
    out = []
    for src in mp._PRECEDENCE:                              # type: ignore
        c = prim.get(src, 0)
        if c:
            out.append((src, c, blurb.get(src, "")))
    return out


_SNAPSHOT: dict | None = None


def project_snapshot() -> dict:
    """Collect one coherent view for every generated living document."""
    global _SNAPSHOT
    if _SNAPSHOT is None:
        q = queue_counts()
        ok, exp, present = oracle()
        total_stubs, per = stub_counts()
        inv = inventory()
        code_pct, fn_done, fn_total, built = completion()
        all_stubs, _ = stub_counts(us_only=False)
        overlays = len({r["overlay"] for r in raw_rows() if r.get("overlay")})
        _SNAPSHOT = {
            "queue": q, "oracle": (ok, exp, present),
            "stubs": (total_stubs, per, all_stubs), "inventory": inv,
            "completion": (code_pct, fn_done, fn_total, built),
            "overlays": overlays,
        }
    return _SNAPSHOT


def status_block() -> str:
    snap = project_snapshot()
    q = snap["queue"]
    ok, exp, present = snap["oracle"]
    total_stubs, per, all_stubs = snap["stubs"]
    inv = snap["inventory"]
    code_pct, fn_done, fn_total, built = snap["completion"]
    overlays = snap["overlays"]
    order = ["matched", "todo", "escalated", "deferred", "near", "claimed"]
    qbits = ", ".join(f"**{q[k]} {k}**" if k == "matched" else f"{q[k]} {k}"
                      for k in order if q.get(k))
    areas = ", ".join(f"{n} `{a}`" for a, n in
                      sorted(per.items(), key=lambda kv: -kv[1]))
    oracle_cell = (f"**{ok} / {exp}** overlay SHA-1s in `config/check.us.sha`"
                   if present else
                   "no build artifacts on disk; run `make build` then re-run")
    completion_cell = (
        f"**{code_pct:.1f}%** ({fn_done} / {fn_total} functions) across "
        f"{built} built binaries"
        if built and fn_total else
        "no linker maps on disk; run `make build` then re-run"
    )
    return "\n".join([
        STATUS_BEGIN,
        GENERATED,
        "",
        "| | |",
        "|---|---|",
        f"| Build oracle | {oracle_cell} |",
        f"| Code decompiled | {completion_cell} |",
        f"| Queue | {q.get('total', sum(q.get(k, 0) for k in order))} "
        f"records: {qbits} |",
        f"| `INCLUDE_ASM` stubs left in `src/` | {total_stubs} ({areas}) |",
        f"| Automation | {inv['modules']} Python modules, {inv['suites']} test "
        f"suites plus {inv['selftests']} modules with their own `--self-test`, "
        f"{inv['tools']} connector tools, {inv['diagnostics']} diagnostics |",
        "",
        f"The `matched` count is *our* work, across {overlays} overlays. The "
        f"stub count is `us` only: it excludes `saturn` and the `_psp` trees, "
        f"which the queue and the oracle also exclude. Counting every `.c` "
        f"under `src/` instead gives {all_stubs}, most of it a Saturn port by "
        f"an external team.",
        STATUS_END,
    ])


def live_status_block() -> str:
    """Compact shared snapshot for living operational documents."""
    snap = project_snapshot()
    q = snap["queue"]
    ok, exp, present = snap["oracle"]
    total_stubs, _per, _all_stubs = snap["stubs"]
    inv = snap["inventory"]
    code_pct, fn_done, fn_total, _built = snap["completion"]
    prov = provenance_rows()
    prov_text = ", ".join(f"{name} {count}" for name, count, _why in prov)
    oracle_text = f"{ok}/{exp}" if present else "no artifacts"
    queue_total = q.get("total", sum(q.values()))
    queue_text = ", ".join(
        f"{q.get(name, 0)} {name}"
        for name in ("matched", "todo", "escalated", "deferred", "near", "claimed")
        if q.get(name, 0)
    )
    return "\n".join([
        LIVE_STATUS_BEGIN,
        "## Live project status",
        "",
        GENERATED,
        "",
        "| live authority | current value |",
        "|---|---|",
        f"| Build oracle | **{oracle_text}** from the artifacts on disk |",
        f"| Decompiled | **{code_pct:.1f}%**, {fn_done}/{fn_total} functions; "
        f"{total_stubs} US `INCLUDE_ASM` stubs remain |",
        f"| Queue | {queue_total} records: {queue_text} |",
        f"| Provenance | {prov_text} |",
        f"| Automation | {inv['modules']} modules, {inv['suites']} suites plus "
        f"{inv['selftests']} module self-tests, {inv['tools']} tools, "
        f"{inv['diagnostics']} diagnostics |",
        "",
        "This block is regenerated from the same queue, checksum manifest, "
        "linker maps, provenance classifier, and connector inventory as `README.md`.",
        LIVE_STATUS_END,
    ])


def work_scope_block() -> str:
    """Exact per-overlay workload from queue coverage's scope authority."""
    from collections import Counter

    by = queue_coverage_collect()
    rows = []
    blind_total = stale_total = 0
    for overlay in sorted(by):
        stubs = by[overlay]["stubs"]
        records = by[overlay]["records"]
        blind = stubs - set(records)
        stale = {fn for fn, status in records.items()
                 if status != "matched" and fn not in stubs}
        blind_total += len(blind)
        stale_total += len(stale)
        counts = Counter(records.values())
        if stubs or any(counts.get(s) for s in
                        ("todo", "near", "escalated", "deferred", "claimed")):
            rows.append((overlay, len(stubs), counts))
    gaps = required_scope_gaps()
    scope_text = (
        f"{len(REQUIRED_US_ARTIFACTS)} checksum artifacts and "
        f"{len(REQUIRED_US_CONFIGS)} splat configs; "
        f"{len(gaps)} scope gaps, {blind_total} blind stubs, "
        f"{stale_total} stale active records"
    )
    lines = [
        WORK_SCOPE_BEGIN,
        "## Live US work scope",
        "",
        GENERATED,
        "",
        scope_text + ".",
        "",
        "| overlay | stubs | todo | near | escalated | deferred | matched |",
        "|---|---:|---:|---:|---:|---:|---:|",
    ]
    for overlay, stubs, counts in rows:
        lines.append(
            f"| `{overlay}` | {stubs} | {counts.get('todo', 0)} | "
            f"{counts.get('near', 0)} | {counts.get('escalated', 0)} | "
            f"{counts.get('deferred', 0)} | {counts.get('matched', 0)} |"
        )
    if gaps:
        lines += ["", "Scope gaps: " + ", ".join(f"`{g}`" for g in gaps)]
    lines += [
        "",
        "This table is generated from the checksum manifest, required config "
        "policy, live `INCLUDE_ASM` inventory, and scheduler-owned queue. "
        "Matched-only overlays are omitted because they carry no remaining work.",
        WORK_SCOPE_END,
    ]
    return "\n".join(lines)


def provenance_block() -> str:
    rows = provenance_rows()
    total = sum(c for _s, c, _b in rows)
    lines = [PROV_BEGIN, GENERATED, "",
             "| source | count | share | what it means |", "|---|---|---|---|"]
    for src, c, why in rows:
        pct = f"{100.0 * c / total:.0f}%" if total else "-"
        lines.append(f"| {src} | {c} | {pct} | {why} |")
    if not rows:
        lines.append("| (match_provenance produced no rows) | | | |")

    # THE CAVEATS ARE DERIVED TOO. They used to be hand-written under the
    # table and said "21% is unattributed, 36 overwritten, 51 never noted"
    # while the table said 28% -- two views of one dataset, synchronised by
    # hand, drifting the moment either was regenerated.
    raw = raw_rows()
    unknown = [r for r in raw if r["primary"] == "unknown"]
    overwritten = sum(1 for r in unknown if r.get("note_overwritten"))
    blank = len(unknown) - overwritten
    fleet_sole = next((c for s, c, _b in rows if s == "model-fleet"), 0)
    fleet_touched = sum(1 for r in raw
                        if "model-fleet" in (r.get("contributors") or []))
    lines += [
        "",
        "Two things this table is honest about, because a progress number "
        "that flatters itself is useless for deciding what to build next:",
        "",
        # `note_overwritten` fires only when the note is PURELY a build
        # receipt, so the remainder is "carries nothing this tool can
        # classify", NOT "was never written". Calling it blank would assert
        # something the data does not say -- the earlier hand-written version
        # did exactly that, splitting 36/51 as overwritten/never-noted.
        f"- **{len(unknown)} of {total} are unattributed, and that is not "
        f"shrinking on its own.** {overwritten} were overwritten outright by "
        f"a build receipt (`scheduler.py report` replaces `notes` wholesale); "
        f"the other {blank} carry no method evidence this tool will accept, "
        f"which is a weaker claim than saying they are empty. Recoverable "
        f"going forward, not for these records; `match_provenance.py "
        f"--unknown` lists them.",
        f"- **The categories overlap.** Each match is counted once, by "
        f"whichever step was DECISIVE. The model fleet is sole author of "
        f"{fleet_sole} but contributed to {fleet_touched}; a model draft the "
        f"permuter drove to zero counts as `permuter`, deliberately, because "
        f"crediting the model would overstate the fleet.",
        f"- **`transplant` is separate from `twin-port` on purpose.** Both "
        f"move a body from a sibling overlay, but a twin-port had its "
        f"divergences worked out by hand while a transplant was placed "
        f"mechanically with the substitutions derived from an asm diff. They "
        f"need different follow-up, so they are not pooled.",
    ]
    lines.append(PROV_END)
    return "\n".join(lines)


def completion_block() -> str:
    """The detailed completion table from the same rows as the headline."""
    sys.path.insert(0, str(AUTO))
    import progress_table as pt                             # type: ignore
    rows = completion_rows()
    if not rows:
        raise RuntimeError("no linker-map completion rows; refusing to replace "
                           "README completion with an empty block")
    return "\n".join([
        COMPLETION_BEGIN,
        GENERATED,
        "",
        pt.markdown(rows),
        COMPLETION_END,
    ])


# ---------------------------------------------------------------------------
# Doc drift.
#
# On 2026-08-15 an audit re-reported five findings from the 2026-08-02 drift
# audit that had already been fixed, and missed that a sixth had not been. Both
# halves of that are the same problem: nothing checks the docs against the code,
# so a finding stays "found" until someone reads it again, and a fix stays
# unverified until someone trips over it.
#
# These four invariants are the ones that actually rotted. Each has a single
# machine-readable ground truth in the repo, which is the bar for being here: a
# check that needs a human to say what the right answer is has not removed any
# work. Anything softer stays a human judgement and does not belong in CI.

# Files that talk about the old state ON PURPOSE. Listed explicitly, with the
# reason, rather than pattern-matched, so that adding an exemption is a visible
# decision and not a quiet way to make the check shut up.
DRIFT_EXEMPT = {
    "docs/audit": "audit files record what was true when they were written",
    "docs/benchmarks": "benchmark receipts preserve the measured baseline",
    "docs/queue-evidence-recovery-2026-08-17.md": "recovery receipts preserve the verified baseline",
    "docs/superpowers/specs": "dated design records preserve their acceptance baseline",
    "SOTN-Orchestration-Stack.md": "2026-06 design doc, predates the harness",
    "SOTN-Orchestration-Action-Plan.md": "2026-06 design doc, same",
    "ORCHESTRATOR.local.md": "names the legacy path to identify it as legacy",
}
# A line stating history is not drift. `was`, a date, or an explicit legacy or
# staleness marker all mean the author knew the number had moved.
RX_HISTORICAL = re.compile(
    r"20\d\d-\d\d-\d\d|\bwas\b|\blegacy\b|\bstale\b|\bNOT\b|\bnever\b|"
    r"\bsuperseded\b|\bRETRACTED\b", re.I)
RX_SELF_RATIO = re.compile(r"\b(\d{2,3})\s*/\s*(\d{2,3})\b")
RX_N_HASHES = re.compile(r"\ball (\d{2,3}) hashes\b")
# `N/N` on its own is not a hash claim. The first version of this check flagged
# `19/19 matched` in a harvest table and three `18/18` model-answer counts in
# fleet-dead-time.md. A ratio only means the oracle if the line says so, and
# requiring that costs nothing: every real instance names the thing it checked.
RX_ORACLE_CTX = re.compile(
    r"\bhash|\bverify_build\b|\boracle\b|check\.us\.sha|PHASE 0|\bSHA-1\b", re.I)


# Prose wraps, so the marker that makes a statement historical is often on a
# neighbouring line: ROADMAP.md says "A 77/77 result now" on one line and "means
# a stale tree" on the next, and ORCHESTRATOR.md dates an incident two lines
# above the sentence describing it. Judging each line alone flagged both. A
# small window is the difference between a check that gets read and one that
# gets muted.
_CTX = 2


def _historical(lines: list[str], i: int) -> bool:
    # A completed roadmap ledger row is durable outcome evidence, not a live
    # assertion. Its then-current oracle result must survive later scope growth.
    if re.match(r"^\|\s*\d+\s*\|\s*(?:done|void|superseded)\s*\|",
                lines[i], re.I):
        return True
    lo, hi = max(0, i - _CTX), min(len(lines), i + _CTX + 1)
    if any(RX_HISTORICAL.search(ln) for ln in lines[lo:hi]):
        return True
    # Snapshot headings can be several table lines above the ratio they govern.
    # Stop at the nearest heading so a historical section cannot exempt a later
    # live section merely because both are in the same document.
    for j in range(i, -1, -1):
        if lines[j].lstrip().startswith("#"):
            return bool(RX_HISTORICAL.search(lines[j]))
    return False


def _inside_generated_block(lines: list[str], i: int) -> bool:
    """Whether line i is owned by one of this module's generated markers."""
    pairs = (
        (STATUS_BEGIN, STATUS_END),
        (PROV_BEGIN, PROV_END),
        (COMPLETION_BEGIN, COMPLETION_END),
        (LIVE_STATUS_BEGIN, LIVE_STATUS_END),
        (WORK_SCOPE_BEGIN, WORK_SCOPE_END),
    )
    for begin, end in pairs:
        start = next((j for j in range(i, -1, -1) if begin in lines[j]), None)
        if start is None:
            continue
        finish = next((j for j in range(start, len(lines)) if end in lines[j]), None)
        if finish is not None and start <= i <= finish:
            return True
    return False


# Pruned during the walk, not filtered after it: rglob descends into .git and
# build/ before the filter can reject anything, and this repo is on a drvfs
# mount where every stat crosses a filesystem boundary. Pruning is the obviously
# right shape regardless of what it saves. (An earlier version of this comment
# claimed it saved 80s. It did not: that number was job-queue wait time on an
# exclusive lock, and I never measured the walk itself.) These hold no prose we
# author.
SKIP_DIRS = {".git", "build", "node_modules", ".venv", "__pycache__",
             "expected", "disks", "assets", "tools"}


_MD_CACHE: list[tuple[Path, list[str]]] | None = None


def _md_lines() -> list[tuple[Path, list[str]]]:
    """(path, lines) for every doc we author, read ONCE.

    The hash and queue-path checks each want every line of every doc. Walking
    and reading twice took this module's self-test from 16s to 153s and made it
    the longest suite in the repo by an order of magnitude, on a drvfs mount
    where each read crosses a filesystem boundary. Same answer, one pass.
    """
    global _MD_CACHE
    if _MD_CACHE is None:
        _MD_CACHE = [
            (p, p.read_text(encoding="utf-8", errors="replace").splitlines())
            for p in _md_files()
        ]
    return _MD_CACHE


def _md_files() -> list[Path]:
    """Tracked Markdown we author, minus exempt paths.

    Walking from REPO recursively stats every candidate and history directory.
    On the Windows-mounted tree that took over 106 seconds. Git already owns the
    tracked-file index, so ask it for the exact Markdown set. Keep the directory
    walk only as a portability fallback when git is unavailable.
    """
    listed = _run(["git", "ls-files", "--", "*.md"], timeout=30)
    if listed:
        out = []
        for rel in listed.splitlines():
            rel = rel.strip()
            if not rel or any(part in rel for part in DRIFT_EXEMPT):
                continue
            p = REPO / rel
            if p.is_file():
                out.append(p)
        return sorted(out)

    out, stack = [], [REPO]
    while stack:
        d = stack.pop()
        try:
            entries = list(d.iterdir())
        except OSError:
            continue
        for p in entries:
            if p.is_dir():
                if p.name not in SKIP_DIRS:
                    stack.append(p)
            elif p.suffix == ".md":
                rel = p.relative_to(REPO).as_posix()
                if not any(part in rel for part in DRIFT_EXEMPT):
                    out.append(p)
    return sorted(out)


def _oracle_truth() -> int:
    """Hash count from config/check.us.sha, which IS the oracle."""
    f = REPO / "config" / "check.us.sha"
    if not f.exists():
        return 0
    return sum(1 for ln in f.read_text(encoding="utf-8").splitlines() if ln.strip())


def drift_hashes() -> list[str]:
    """Mutable oracle totals must live inside generated blocks."""
    truth = _oracle_truth()
    if not truth:
        return ["config/check.us.sha missing or empty; cannot check hash counts"]
    bad = []
    for p, lines in _md_lines():
        for i, line in enumerate(lines, 1):
            if _historical(lines, i - 1):
                continue
            hits = set()
            if RX_ORACLE_CTX.search(line):
                hits |= {int(m.group(1)) for m in RX_SELF_RATIO.finditer(line)
                         if m.group(1) == m.group(2)}
            hits |= {int(m.group(1)) for m in RX_N_HASHES.finditer(line)}
            for n in sorted(hits):
                rel = p.relative_to(REPO).as_posix()
                if _inside_generated_block(lines, i - 1):
                    if n != truth:
                        bad.append(f"{rel}:{i}: generated block says {n}, "
                                   f"oracle has {truth}: {line.strip()[:70]}")
                else:
                    bad.append(f"{rel}:{i}: hard-coded live oracle total {n}; "
                               f"use a generated block or numberless wording: "
                               f"{line.strip()[:70]}")
    return bad


def drift_queue_path() -> list[str]:
    """Docs presenting the legacy in-repo queue as the live one.

    A file-sync daemon destroyed the in-repo queue once, which is why it moved.
    A doc that sends someone back to it is not cosmetic.
    """
    sched = (AUTO / "scheduler.py").read_text(encoding="utf-8", errors="replace")
    if "~/sotn-work/queue.jsonl" not in sched:
        return ["scheduler.py no longer defaults to ~/sotn-work/queue.jsonl; "
                "this check encodes the wrong truth and must be updated"]
    bad = []
    for p, lines in _md_lines():
        for i, line in enumerate(lines, 1):
            if "work/queue.jsonl" not in line or "sotn-work/queue.jsonl" in line:
                continue
            if _historical(lines, i - 1):
                continue
            bad.append(f"{p.relative_to(REPO).as_posix()}:{i}: presents the "
                       f"legacy path as live: {line.strip()[:70]}")
    return bad


def drift_component_table() -> list[str]:
    """Scripts the architecture doc says are runnable, that are not allowlisted.

    This is the one the 2026-08-15 audit got right: overlay_size_check.py was in
    the table and wired to a dashboard button, but absent from AUTOMATION_SCRIPTS,
    so both paths failed only when used. The reverse is NOT checked -- the table
    is a curated eight, not an index of all 56 allowlisted scripts.
    """
    doc = REPO / "docs" / "HARNESS-ARCHITECTURE.md"
    if not doc.exists():
        return ["docs/HARNESS-ARCHITECTURE.md missing"]
    text = doc.read_text(encoding="utf-8", errors="replace")
    m = re.search(
        r"runnable via `run_automation`[.:](.+?)(?:\n#|\Z)", text, re.S)
    if not m:
        return ["the 'runnable via run_automation' table is gone from "
                "HARNESS-ARCHITECTURE.md; this check no longer verifies anything"]
    listed = set(re.findall(r"`([A-Za-z0-9_]+\.py)`", m.group(1)))
    if not listed:
        return ["found the run_automation section but no scripts in it"]
    # Read the allowlist as TEXT rather than importing commands_client. Pulling
    # in the whole connector to read one tuple means executing a module with
    # side effects inside a read-only doc check, which is the wrong trade
    # whatever it costs.
    allow = (AUTO / "mcp" / "commands_client.py").read_text(
        encoding="utf-8", errors="replace")
    m2 = re.search(r"AUTOMATION_SCRIPTS\s*=\s*[({](.+?)[)}]", allow, re.S)
    if not m2:
        return ["cannot find AUTOMATION_SCRIPTS in commands_client.py; this "
                "check no longer verifies anything"]
    allowed = set(re.findall(r"[\"']([A-Za-z0-9_]+\.py)[\"']", m2.group(1)))
    if not allowed:
        return ["AUTOMATION_SCRIPTS parsed as empty; refusing to report every "
                "script as missing"]
    missing = sorted(listed - allowed)
    return [f"HARNESS-ARCHITECTURE.md offers {s} as runnable, but it is not in "
            f"AUTOMATION_SCRIPTS, so run_automation rejects it" for s in missing]


def _inclusive_block(text: str, begin: str, end: str) -> str | None:
    """Return exactly one ordered marker-delimited block, normalized to LF."""
    if text.count(begin) != 1 or text.count(end) != 1:
        return None
    i = text.find(begin)
    j = text.find(end)
    if i < 0 or j < i + len(begin):
        return None
    return text[i:j + len(end)].replace("\r\n", "\n")


def _generated_block_findings(
        text: str, expected: tuple[tuple[str, str, str, str], ...],
        document: str = "README.md",
) -> list[str]:
    """Compare marker-delimited text with generated blocks."""
    bad = []
    for name, begin, end, block in expected:
        begin_count, end_count = text.count(begin), text.count(end)
        if begin_count != 1 or end_count != 1:
            bad.append(
                f"{document} {name} markers are not unique: begin="
                f"{begin_count}, end={end_count}; expected one of each"
            )
            continue
        actual = _inclusive_block(text, begin, end)
        if actual is None:
            bad.append(f"{document} {name} markers are out of order")
        elif actual != block.replace("\r\n", "\n"):
            bad.append(f"{document} {name} block is stale; run "
                       "automation/readme_status.py --write")
    return bad


def generated_documents() -> dict[Path, tuple[tuple[str, str, str, str], ...]]:
    """Every managed path and its marker-delimited generated blocks."""
    docs = {
        README: (
            ("status", STATUS_BEGIN, STATUS_END, status_block()),
            ("provenance", PROV_BEGIN, PROV_END, provenance_block()),
            ("completion", COMPLETION_BEGIN, COMPLETION_END, completion_block()),
        )
    }
    shared = live_status_block()
    for rel in LIVE_STATUS_DOCS:
        existing = docs.get(REPO / rel, ())
        docs[REPO / rel] = existing + (
            ("live status", LIVE_STATUS_BEGIN, LIVE_STATUS_END, shared),
        )
    for rel in WORK_SCOPE_DOCS:
        existing = docs.get(REPO / rel, ())
        docs[REPO / rel] = existing + (
            ("work scope", WORK_SCOPE_BEGIN, WORK_SCOPE_END, work_scope_block()),
        )
    return docs


def drift_generated_documents() -> list[str]:
    """Every generated block must equal the shared live generators exactly."""
    bad = []
    for path, expected in generated_documents().items():
        rel = path.relative_to(REPO).as_posix()
        if not path.exists():
            bad.append(f"{rel} is missing")
            continue
        text = path.read_text(encoding="utf-8", errors="replace")
        bad.extend(_generated_block_findings(text, expected, rel))
    return bad


DRIFT_CHECKS = (
    ("hash count", drift_hashes),
    ("queue path", drift_queue_path),
    ("component table", drift_component_table),
    ("generated living documents", drift_generated_documents),
)


def drift_report(timings: bool = False) -> tuple[str, int]:
    """(text, number of findings). Read-only; never builds."""
    lines, total = [], 0
    for name, fn in DRIFT_CHECKS:
        started = time.perf_counter()
        try:
            found = fn()
        except Exception as e:                              # noqa: BLE001
            found = [f"check itself failed: {e!r}"]
        elapsed = time.perf_counter() - started
        total += len(found)
        suffix = f" [{elapsed:.3f}s]" if timings else ""
        lines.append(f"{name}: {'clean' if not found else str(len(found)) + ' finding(s)'}{suffix}")
        lines.extend("  " + f for f in found)
    lines.append("")
    lines.append(f"{total} finding(s). These are the invariants with a single "
                 f"machine-readable ground truth in the repo; everything else "
                 f"about doc accuracy is still a human read.")
    return "\n".join(lines), total


def splice(text: str, begin: str, end: str, block: str,
           document: str = "document") -> str:
    """Replace between markers. Missing markers is an ERROR, not an append.

    Appending would silently produce two status tables, and the stale one
    would keep being read. Say the markers are absent and change nothing.
    """
    begin_count, end_count = text.count(begin), text.count(end)
    if begin_count != 1 or end_count != 1:
        raise LookupError(
            f"expected exactly one {begin} and one {end} in {document}; "
            f"found {begin_count} and {end_count}"
        )
    i, j = text.find(begin), text.find(end)
    if j < i + len(begin):
        raise LookupError(f"markers {begin} .. {end} are out of order")
    return text[:i] + block + text[j + len(end):]


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--write", action="store_true",
                    help="update all managed living documents in place")
    ap.add_argument("--drift", action="store_true",
                    help="check docs against code for the four invariants "
                          "that have actually rotted; exit 1 if any drifted")
    ap.add_argument("--self-test", action="store_true")
    ap.add_argument("--timings", action="store_true",
                    help="include per-check elapsed time in --drift output")
    ap.add_argument("--managed-paths", action="store_true",
                    help="print managed document paths and exit")
    a = ap.parse_args()
    if a.managed_paths:
        print("\n".join(("README.md",) + LIVE_STATUS_DOCS))
        return 0
    if a.self_test:
        return self_test()
    if a.drift:
        text, n = drift_report(timings=a.timings)
        print(text)
        # Non-zero so this can gate a commit. The first three checks inspect
        # hand-written claims; the fourth proves generated blocks were refreshed.
        return 1 if n else 0

    sb, pb, cb = status_block(), provenance_block(), completion_block()
    if not a.write:
        print(sb + "\n\n" + pb + "\n\n" + cb)
        print("\n(nothing written; pass --write)")
        return 0
    rendered: dict[Path, str] = {}
    try:
        for path, expected in generated_documents().items():
            rel = path.relative_to(REPO).as_posix()
            text = path.read_text(encoding="utf-8")
            for _name, begin, end, block in expected:
                text = splice(text, begin, end, block, rel)
            rendered[path] = text
    except (LookupError, OSError) as e:
        print(f"refused before writing any document: {e}", file=sys.stderr)
        return 1
    for path, text in rendered.items():
        tmp = path.with_name(path.name + ".readme-status.tmp")
        tmp.write_text(text, encoding="utf-8")
        tmp.replace(path)
    print(f"updated {len(rendered)} managed living documents")
    return 0


def self_test() -> int:
    fails = []

    def ck(c, label, detail=""):
        print(("  ok   " if c else "  FAIL ") + label
              + ("" if c else "   " + detail))
        if not c:
            fails.append(label)

    print("\nevery provenance source the table can print has an explanation")
    # The provenance table iterates match_provenance._PRECEDENCE, so a source
    # added there appears here whether or not anyone wrote a description for
    # it. `upstream-harvest` did exactly that on 2026-08-16 and rendered as a
    # count of 25 beside an empty cell -- the biggest row in the table saying
    # nothing. Asserting the two lists agree costs nothing and closes it.
    sys.path.insert(0, str(AUTO))
    import match_provenance as _mp                            # type: ignore
    _blurbs = {
        "upstream-harvest", "shim-segment", "shim-header", "transplant",
        "twin-port", "permuter", "model-fleet", "claude-manual", "unknown",
    }
    _missing = [s for s in _mp._PRECEDENCE if s not in _blurbs]
    ck(not _missing,
       "no source in _PRECEDENCE lacks a blurb", f"missing: {_missing}")
    _extra = [s for s in _blurbs if s not in _mp._PRECEDENCE]
    ck(not _extra,
       "and no blurb describes a source that no longer exists",
       f"stale: {_extra}")

    print("\nthe drift checks are anchored to code, not to a remembered number")
    _md_source = Path(__file__).read_text(encoding="utf-8")
    _md_start = _md_source.index("def _md_files(")
    _md_end = _md_source.index("\\ndef ", _md_start + 1)
    _md_body = _md_source[_md_start:_md_end]
    ck('["git", "ls-files", "--", "*.md"]' in _md_body
       and _md_body.index('["git", "ls-files", "--", "*.md"]')
           < _md_body.index("out, stack = [], [REPO]"),
       "Markdown discovery uses the tracked-file index before its fallback walk")

    truth = _oracle_truth()
    ck(truth > 0, "the oracle hash count is read from config/check.us.sha",
       f"got {truth}")
    # The check has to FIRE on a real regression, or it is decoration. Each of
    # the first three are fed the exact strings that were in the tree when the
    # defects were found. Generated-block staleness is exercised separately.
    import tempfile as _tf
    with _tf.TemporaryDirectory() as d:
        bad = Path(d) / "fake.md"
        bad.write_text(f"expect {truth - 4}/{truth - 4} OK\n"
                       "The live queue lives at work/queue.jsonl\n",
                       encoding="utf-8")
        line1, line2 = bad.read_text(encoding="utf-8").splitlines()
        ck(bool(RX_SELF_RATIO.search(line1)) and not RX_HISTORICAL.search(line1),
           "a bare stale hash ratio is caught")
        ck("work/queue.jsonl" in line2 and "sotn-work" not in line2
           and not RX_HISTORICAL.search(line2),
           "and the legacy queue path presented as live")
    # ...and stay quiet on the sentences deliberately left in place, or it will
    # be ignored inside a week.
    for hist in (f"was {truth - 4}/{truth - 4} before the upstream merge",
                 "(NOT work/queue.jsonl; that path is legacy)",
                 "On 2026-07-19 the baseline was verified clean at 77/77"):
        ck(bool(RX_HISTORICAL.search(hist)),
           f"history is not drift: {hist[:44]!r}")

    print("\nand they pass against the tree as it stands")
    for name, fn in DRIFT_CHECKS:
        found = fn()
        ck(not found, f"{name} is clean", "; ".join(found[:3]))
    ck(len(DRIFT_CHECKS) == 4,
       "four checks, each with one machine-readable ground truth; a check "
       "needing a human to supply the right answer removes no work")

    print("\ngenerated document drift is an exact marker-delimited comparison")
    generated = (
        ("status", STATUS_BEGIN, STATUS_END,
         f"{STATUS_BEGIN}\nnew\n{STATUS_END}"),
        ("provenance", PROV_BEGIN, PROV_END,
         f"{PROV_BEGIN}\nnew\n{PROV_END}"),
        ("completion", COMPLETION_BEGIN, COMPLETION_END,
         f"{COMPLETION_BEGIN}\nnew\n{COMPLETION_END}"),
    )
    stale = (f"{STATUS_BEGIN}\nold\n{STATUS_END}\n"
             f"{PROV_BEGIN}\nold\n{PROV_END}\n"
             f"{COMPLETION_BEGIN}\nold\n{COMPLETION_END}\n")
    stale_findings = _generated_block_findings(stale, generated)
    ck(len(stale_findings) == 3
       and all("stale" in finding for finding in stale_findings),
       "all three stale generated blocks are reported",
       f"got {stale_findings}")
    missing_findings = _generated_block_findings("no markers", generated)
    ck(len(missing_findings) == 3
       and all("begin=0, end=0" in finding for finding in missing_findings),
       "all three missing marker pairs are reported",
       f"got {missing_findings}")
    one = (generated[0],)
    duplicate = generated[0][3] + "\n" + generated[0][3]
    duplicate_findings = _generated_block_findings(duplicate, one)
    ck(len(duplicate_findings) == 1
       and "begin=2, end=2" in duplicate_findings[0],
       "a duplicate complete block is rejected",
       f"got {duplicate_findings}")
    duplicate_begin = (f"{STATUS_BEGIN}\n{STATUS_BEGIN}\nnew\n"
                       f"{STATUS_END}")
    begin_findings = _generated_block_findings(duplicate_begin, one)
    ck(len(begin_findings) == 1
       and "begin=2, end=1" in begin_findings[0],
       "a duplicate individual marker is rejected",
       f"got {begin_findings}")
    one_sided = f"{STATUS_BEGIN}\nnew without an end marker"
    one_sided_findings = _generated_block_findings(one_sided, one)
    ck(len(one_sided_findings) == 1
       and "begin=1, end=0" in one_sided_findings[0],
       "one-sided marker loss is rejected",
       f"got {one_sided_findings}")
    reversed_markers = f"{STATUS_END}\nnew\n{STATUS_BEGIN}"
    reversed_findings = _generated_block_findings(reversed_markers, one)
    ck(len(reversed_findings) == 1
       and "out of order" in reversed_findings[0],
       "one begin and one end in the wrong order are rejected",
       f"got {reversed_findings}")

    print("\nsplice replaces between markers and is idempotent")
    doc = f"before\n{STATUS_BEGIN}\nold\n{STATUS_END}\nafter\n"
    once = splice(doc, STATUS_BEGIN, STATUS_END,
                  f"{STATUS_BEGIN}\nnew\n{STATUS_END}")
    ck("new" in once and "old" not in once, "the block is replaced")
    ck(once.startswith("before") and once.rstrip().endswith("after"),
       "and the surrounding prose survives")
    twice = splice(once, STATUS_BEGIN, STATUS_END,
                   f"{STATUS_BEGIN}\nnew\n{STATUS_END}")
    ck(twice == once, "running it again changes nothing")

    print("\nmissing markers REFUSE rather than appending a second table")
    # Appending would leave two status tables and the stale one would keep
    # being read, which is the failure this tool exists to end.
    try:
        splice("no markers here", STATUS_BEGIN, STATUS_END, "x")
        ck(False, "absent markers raise")
    except LookupError:
        ck(True, "absent markers raise")
    try:
        splice(doc + doc, STATUS_BEGIN, STATUS_END, "x")
        ck(False, "duplicate blocks raise")
    except LookupError:
        ck(True, "duplicate blocks raise")

    print("\nthe README carries the markers this tool needs")
    txt = README.read_text(encoding="utf-8")
    for mk in (STATUS_BEGIN, STATUS_END, PROV_BEGIN, PROV_END,
               COMPLETION_BEGIN, COMPLETION_END, WORK_SCOPE_BEGIN,
               WORK_SCOPE_END):
        ck(mk in txt, f"{mk} present")

    print("\nmutable oracle totals are allowed only inside generated blocks")
    sample = [STATUS_BEGIN, f"oracle {truth}/{truth}", STATUS_END,
              f"oracle {truth}/{truth}"]
    ck(_inside_generated_block(sample, 1),
       "a generated oracle row is recognized as generator-owned")
    ck(not _inside_generated_block(sample, 3),
       "the same literal in prose is not mistaken for generated content")

    print("\nthe live work-scope block uses the exact queue authority")
    ck(not required_scope_gaps(),
       "all required artifacts and configs are present with no extras")
    scope = work_scope_block()
    ck(f"{len(REQUIRED_US_ARTIFACTS)} checksum artifacts" in scope
       and f"{len(REQUIRED_US_CONFIGS)} splat configs" in scope,
       "scope counts come from the required policy tuples")
    ck("0 scope gaps, 0 blind stubs, 0 stale active records" in scope,
       "live queue coverage is exact")
    roadmap_text = (REPO / "ROADMAP.md").read_text(encoding="utf-8")
    ck(roadmap_text.count(WORK_SCOPE_BEGIN) == 1
       and roadmap_text.count(WORK_SCOPE_END) == 1,
       "ROADMAP.md has exactly one shared work-scope marker pair")

    print("\nevery living operational document carries one shared status block")
    ck(len(LIVE_STATUS_DOCS) == len(set(LIVE_STATUS_DOCS)),
       "managed paths are unique")
    for rel in LIVE_STATUS_DOCS:
        managed = (REPO / rel).read_text(encoding="utf-8")
        ck(managed.count(LIVE_STATUS_BEGIN) == 1
           and managed.count(LIVE_STATUS_END) == 1,
           f"{rel} has exactly one live-status marker pair")

    print("\nthe queue row is never rendered empty")
    # `scheduler.py stats` writes `total 470` space-separated and every other
    # row as `   todo: 126`. The first regex required whitespace, matched only
    # `total`, and the table shipped as "470 records:" with nothing after the
    # colon. Assert against the REAL command, not a fixture: the format is the
    # thing that broke.
    q = queue_counts()
    ck(q.get("total", 0) > 0, f"total parsed ({q.get('total')})")
    ck(q.get("matched", 0) > 0, f"matched parsed ({q.get('matched')})")
    ck(len(q) >= 5, f"every status row parsed, not just total ({sorted(q)})")
    ck("records:" not in status_block().split("| Queue |")[1].split("|")[0]
       .replace("records:", "records: ").strip()[-1:],
       "the queue cell is not left dangling after the colon")

    print("\nstubs are counted for the `us` build only")
    # Counting every .c under src/ took this from 775 to 2734, four fifths of
    # it Saturn -- a port by an external team that the queue, the oracle and
    # every other number in this README exclude. A status line that silently
    # changes what it counts looks like progress in reverse.
    total, per = stub_counts()
    ck("saturn" not in per, f"saturn is excluded ({sorted(per)})")
    ck(not any(k.endswith("_psp") for k in per),
       f"and the psp trees are too ({sorted(per)})")
    # NO MAGIC RANGE. My first version asserted 400 < total < 1500, a window
    # drawn around the stale 775 -- which was itself inconsistent, since its
    # own per-area figures summed to 592. Encoding a guessed number in the
    # test for a tool whose whole purpose is to stop guessed numbers is the
    # same mistake one layer up. Assert the SHAPE instead: the areas are the
    # us ones, and the parts add up to the whole.
    ck(total > 0 and set(per) <= {"st", "boss", "main", "servant", "dra",
                                  "ric", "weapon"},
       f"only us build areas are counted ({sorted(per)})")
    ck(total == sum(per.values()),
       f"and the total is the sum of its parts ({total} vs "
       f"{sum(per.values())}), which the old hand-written 775 was not")

    print("\ninventory counts are DISCOVERED, never written down")
    inv = inventory()
    ck(inv["modules"] > 40, f"modules counted ({inv['modules']})")
    ck(inv["suites"] > 15, f"test suites counted ({inv['suites']})")
    ck(inv["suites"] == len(selftest_runner.suites()),
       "suite count comes from the gate's discovery authority")
    ck(inv["selftests"] == len(selftest_runner.selftest_modules()),
       "module self-test count comes from the gate's discovery authority")
    ck(inv["tools"] > 40, f"connector tools counted ({inv['tools']})")
    ck(inv["diagnostics"] > 40, f"diagnostics counted ({inv['diagnostics']})")
    src_self = Path(__file__).read_text(encoding="utf-8")
    ck("AUTOMATION_SCRIPTS" in src_self,
       "diagnostics read the real registry, not a literal")

    print("\nthe completion headline delegates to progress_table")
    cp, fd, ft, built = completion()
    sb = status_block()
    ck(built > 0 and ft > 0,
       f"linker-map completion is available ({fd}/{ft}, {built} binaries)")
    ck(f"**{cp:.1f}%** ({fd} / {ft} functions)" in sb,
       "the status row contains progress_table's live result")

    print("\nthe oracle is READ, never run")
    # A generator that triggers a build would take minutes and need the lock.
    #
    # TEST WHAT IS SPAWNED, NOT WHAT IS SPELLED. The first version forbade the
    # words "make build" anywhere in the file and then failed on its own help
    # text -- the absent-artifacts message says `run make build then re-run`,
    # which is advice, not an invocation. Grepping prose for a verb catches
    # documentation as often as behaviour.
    spawned = re.findall(r"_run\(\[([^\]]*)\]", src_self)
    ck(spawned, f"the subprocess call sites are findable ({len(spawned)})")
    ck(all("scheduler.py" in call or '"git", "ls-files"' in call
           for call in spawned),
       f"and each one is either scheduler stats or tracked Markdown discovery "
       f"({spawned})")
    ck("verify_checksums" in src_self,
       "the oracle is read by hashing artifacts already on disk")

    print("\nand a missing build is reported, not papered over")
    ck("no build artifacts on disk" in src_self,
       "the absent-artifact case has its own message")

    print("\nthe queue is read through the scheduler")
    # THE NEEDLE IS BUILT FROM PARTS. Written literally, the assertion line
    # itself contains "queue" + ".jsonl", so the check finds its own source
    # and fails no matter what the module does. That is the fourth time this
    # exact trap has fired in this repo today; see the dashboard parse check
    # in test_connector_surfaces and _strip_comments_and_strings in
    # worker_direct for the others.
    #
    # It fired a FIFTH time when --drift landed: that check has to name the
    # legacy queue path in order to find docs still pointing at it, so "the
    # string is absent" stopped being true while the property it stood for --
    # this module never READS the queue file -- stayed true. An absence test
    # was the wrong shape; assert the property directly instead.
    needle = "queue" + ".jsonl"
    ck("scheduler.py" in src_self, "the scheduler is invoked")
    reads = [ln.strip() for ln in src_self.splitlines()
             if needle in ln
             and re.search(r"\bopen\s*\(|read_text|read_bytes|readlines", ln)]
    ck(not reads, "and the queue file is never opened directly",
       "; ".join(reads[:2]))

    print()
    if fails:
        print(f"{len(fails)} FAILED:")
        for f in fails:
            print("  - " + f)
        return 1
    print("all checks passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
