#!/usr/bin/env python3
"""Generate the README status tables instead of maintaining them by hand.

WHY THIS EXISTS
    The 2026-08-10 audit flagged README drift as its only red item, and it was
    right: the block said "Measured 2026-08-09" and claimed 198 matched, 184
    todo, 50 escalated, 31 deferred while the live queue held 203 / 126 / 102 /
    33. The provenance table was staler still -- it predates `transplant`
    existing as a source at all, so eight transplanted matches were sitting in
    its 21% `unknown` bucket.

    Every one of those numbers already had a generator. Nobody was running
    them. That is the whole defect, and hand-editing the numbers again would
    just restart the clock.

WHAT IT REGENERATES
    Two fenced blocks, delimited by HTML comment markers so the surrounding
    prose is untouched and re-running is idempotent:

        <!-- STATUS:BEGIN -->      the queue / oracle / inventory table
        <!-- PROVENANCE:BEGIN -->  the how-were-these-matched table

WHAT IT DELIBERATELY DOES NOT TOUCH
    The "Code decompiled 95.2%" figure and the per-binary completion table.
    Those come from `make reports`, they are overwhelmingly upstream's work
    rather than this fork's, and deriving them here would mean a second
    implementation of a number the build already computes. The README says
    where they come from; this tool leaves them alone rather than producing a
    slightly different answer from a different method.

    THE ORACLE IS READ, NEVER RUN. Building takes minutes and needs the lock.
    This hashes whatever artifacts are on disk and reports the result with the
    caveat that it reflects the last build, not this instant. If there are no
    artifacts it says so instead of printing a comforting number.

STRICTLY READ-ONLY unless --write is passed.

Usage:
    python3 automation/readme_status.py            # print, change nothing
    python3 automation/readme_status.py --write    # update README.md
    python3 automation/readme_status.py --self-test
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
AUTO = REPO / "automation"
README = REPO / "README.md"
PYTHON = str(REPO / ".venv" / "bin" / "python")
if not Path(PYTHON).exists():                                # pragma: no cover
    PYTHON = sys.executable

STATUS_BEGIN = "<!-- STATUS:BEGIN -->"
STATUS_END = "<!-- STATUS:END -->"
PROV_BEGIN = "<!-- PROVENANCE:BEGIN -->"
PROV_END = "<!-- PROVENANCE:END -->"

GENERATED = ("*Generated by `automation/readme_status.py`. Do not edit by "
             "hand; run the tool.*")


def _run(args: list[str], timeout: int = 300) -> str:
    try:
        r = subprocess.run(args, cwd=str(REPO), capture_output=True,
                           text=True, timeout=timeout)
        return r.stdout
    except (OSError, subprocess.SubprocessError):
        return ""


def queue_counts() -> dict[str, int]:
    """Through scheduler.py, never off the queue file.

    SOTN_QUEUE resolves per environment, so a direct read answers about a
    different file. deferred_triage documents an incident where a snapshot
    reported 33 matched against a live 134.
    """
    out = _run([PYTHON, str(AUTO / "scheduler.py"), "stats"])
    counts: dict[str, int] = {}
    for line in out.splitlines():
        # `total 470` is space-separated; every other row is `   todo: 126`.
        # The first version required whitespace and so matched ONLY `total`,
        # and the generated table shipped as "470 records:" with nothing after
        # the colon. An empty rendering is the one outcome a status generator
        # must not produce quietly.
        m = re.match(r"\s*(\w+)[:\s]\s*(\d+)\s*$", line)
        if m:
            counts[m.group(1)] = int(m.group(2))
    return counts


def oracle() -> tuple[int, int, bool]:
    """(matched, expected, artifacts_present) from the LAST build. Read-only."""
    sys.path.insert(0, str(AUTO))
    try:
        from permuter_supervisor import verify_checksums   # type: ignore
    except Exception:                                       # noqa: BLE001
        return (0, 0, False)
    try:
        ok, detail = verify_checksums("us")
    except Exception:                                       # noqa: BLE001
        return (0, 0, False)
    m = re.search(r"(\d+)\s*/\s*(\d+)", detail or "")
    if not m:
        return (0, 0, False)
    return (int(m.group(1)), int(m.group(2)), True)


# Areas that are not part of the `us` build this README measures. Counting
# them took the figure from 775 to 2734, four fifths of it Saturn -- a port by
# an external team that the queue, the oracle and every other number here
# exclude by design. A status line that silently changes what it counts is
# worse than a stale one, because it looks like progress in reverse.
NON_US = ("saturn",)
NON_US_SUFFIX = ("_psp",)


def stub_counts(us_only: bool = True) -> tuple[int, dict[str, int]]:
    """INCLUDE_ASM stubs left in src/, by top-level area.

    us_only=False is used ONLY to state, in the README, how much bigger the
    number gets when the non-us trees are included. Quoting the difference is
    what stops the next reader assuming the figure shrank.
    """
    rx = re.compile(r"^\s*INCLUDE_ASM\(", re.M)
    per: dict[str, int] = {}
    total = 0
    for p in (REPO / "src").rglob("*.c"):
        parts = p.relative_to(REPO / "src").parts
        if us_only and (parts[0] in NON_US or any(
                seg.endswith(NON_US_SUFFIX) for seg in parts[:-1])):
            continue
        try:
            n = len(rx.findall(p.read_text(errors="ignore")))
        except OSError:
            continue
        if not n:
            continue
        total += n
        area = p.relative_to(REPO / "src").parts[0]
        per[area] = per.get(area, 0) + n
    return total, per


def inventory() -> dict[str, int]:
    """Counts that are DISCOVERED, not written down.

    Every one of these was a hand-maintained number somewhere at some point,
    and every hand-maintained number in this repo has drifted: fleet_start's
    help omitted `zen` for weeks, run_analysis's docstring listed seven of
    forty-five scripts, match_provenance enumerated two `_from_` suffixes out
    of five. Count them.
    """
    mods = [p for p in AUTO.rglob("*.py") if ".venv" not in p.parts]
    suites = sorted(AUTO.glob("test_*.py"))
    # Modules carrying their own --self-test, the way run_selftests finds them.
    selftests = 0
    for p in mods:
        if p.name.startswith("test_"):
            continue
        try:
            if "--self-test" in p.read_text(errors="ignore"):
                selftests += 1
        except OSError:
            pass
    tools = 0
    for name in ("sotn_cmd_mcp.py", "sotn_local_mcp.py"):
        f = AUTO / "mcp" / name
        if f.is_file():
            tools += len(re.findall(r"@mcp\.tool\(\)",
                                    f.read_text(errors="ignore")))
    diagnostics = 0
    try:
        sys.path.insert(0, str(AUTO / "mcp"))
        import commands_client as cc                        # type: ignore
        diagnostics = len(cc.ANALYSIS_SCRIPTS)
    except Exception:                                       # noqa: BLE001
        pass
    return {"modules": len(mods), "suites": len(suites),
            "selftests": selftests, "tools": tools,
            "diagnostics": diagnostics}


_RAW: list[dict] | None = None


def raw_rows() -> list[dict]:
    """match_provenance's per-record attribution, computed once and shared.

    THE TABLE AND THE PROSE MUST COME FROM ONE READ. They did not: the table
    said 28% unknown while the paragraph under it said 21%, and that paragraph
    also broke the figure down as "36 overwritten, 51 never noted" against a
    total that had moved twice. Two hand-synchronised views of one dataset
    drift the moment either is regenerated alone.
    """
    global _RAW
    if _RAW is None:
        sys.path.insert(0, str(AUTO))
        import match_provenance as mp                       # type: ignore
        try:
            recs = mp.load_queue()                          # type: ignore
            _RAW = mp.analyse(recs, use_git=False, jobs=1,  # type: ignore
                              progress=False)
        except Exception as e:                              # noqa: BLE001
            raise RuntimeError(
                f"match_provenance failed: {type(e).__name__}: {e}")
    return _RAW


def provenance_rows() -> list[tuple[str, int, str]]:
    """(source, count, blurb) from match_provenance, in its own precedence."""
    sys.path.insert(0, str(AUTO))
    import match_provenance as mp                           # type: ignore
    rows = raw_rows()
    from collections import Counter
    prim = Counter(r["primary"] for r in rows)
    blurb = {
        "shim-segment": "shared header plus splat segment work",
        "shim-header": "body copied from a shared header",
        "transplant": "transplant.py moved a twin body in mechanically",
        "twin-port": "ported from a sibling overlay or RIC, by hand",
        "permuter": "decomp-permuter search reached 0",
        "model-fleet": "an OpenCode or llama worker wrote it",
        "claude-manual": "written or repaired by hand",
        "unknown": "evidence insufficient; **not** a guess",
    }
    out = []
    for src in mp._PRECEDENCE:                              # type: ignore
        c = prim.get(src, 0)
        if c:
            out.append((src, c, blurb.get(src, "")))
    return out


def status_block() -> str:
    q = queue_counts()
    ok, exp, present = oracle()
    total_stubs, per = stub_counts()
    inv = inventory()
    all_stubs, _ = stub_counts(us_only=False)
    overlays = len({r["overlay"] for r in raw_rows() if r.get("overlay")})
    order = ["matched", "todo", "escalated", "deferred", "near", "claimed"]
    qbits = ", ".join(f"**{q[k]} {k}**" if k == "matched" else f"{q[k]} {k}"
                      for k in order if q.get(k))
    areas = ", ".join(f"{n} `{a}`" for a, n in
                      sorted(per.items(), key=lambda kv: -kv[1]))
    oracle_cell = (f"**{ok} / {exp}** overlay SHA-1s in `config/check.us.sha`"
                   if present else
                   "no build artifacts on disk; run `make build` then re-run")
    return "\n".join([
        STATUS_BEGIN,
        GENERATED,
        "",
        "| | |",
        "|---|---|",
        f"| Build oracle | {oracle_cell} |",
        f"| Queue | {q.get('total', sum(q.get(k, 0) for k in order))} "
        f"records: {qbits} |",
        f"| `INCLUDE_ASM` stubs left in `src/` | {total_stubs} ({areas}) |",
        f"| Automation | {inv['modules']} Python modules, {inv['suites']} test "
        f"suites plus {inv['selftests']} modules with their own `--self-test`, "
        f"{inv['tools']} connector tools, {inv['diagnostics']} diagnostics |",
        "",
        f"The `matched` count is *our* work, across {overlays} overlays. The "
        f"stub count is `us` only: it excludes `saturn` and the `_psp` trees, "
        f"which the queue and the oracle also exclude. Counting every `.c` "
        f"under `src/` instead gives {all_stubs}, most of it a Saturn port by "
        f"an external team.",
        STATUS_END,
    ])


def provenance_block() -> str:
    rows = provenance_rows()
    total = sum(c for _s, c, _b in rows)
    lines = [PROV_BEGIN, GENERATED, "",
             "| source | count | share | what it means |", "|---|---|---|---|"]
    for src, c, why in rows:
        pct = f"{100.0 * c / total:.0f}%" if total else "-"
        lines.append(f"| {src} | {c} | {pct} | {why} |")
    if not rows:
        lines.append("| (match_provenance produced no rows) | | | |")

    # THE CAVEATS ARE DERIVED TOO. They used to be hand-written under the
    # table and said "21% is unattributed, 36 overwritten, 51 never noted"
    # while the table said 28% -- two views of one dataset, synchronised by
    # hand, drifting the moment either was regenerated.
    raw = raw_rows()
    unknown = [r for r in raw if r["primary"] == "unknown"]
    overwritten = sum(1 for r in unknown if r.get("note_overwritten"))
    blank = len(unknown) - overwritten
    fleet_sole = next((c for s, c, _b in rows if s == "model-fleet"), 0)
    fleet_touched = sum(1 for r in raw
                        if "model-fleet" in (r.get("contributors") or []))
    lines += [
        "",
        "Two things this table is honest about, because a progress number "
        "that flatters itself is useless for deciding what to build next:",
        "",
        # `note_overwritten` fires only when the note is PURELY a build
        # receipt, so the remainder is "carries nothing this tool can
        # classify", NOT "was never written". Calling it blank would assert
        # something the data does not say -- the earlier hand-written version
        # did exactly that, splitting 36/51 as overwritten/never-noted.
        f"- **{len(unknown)} of {total} are unattributed, and that is not "
        f"shrinking on its own.** {overwritten} were overwritten outright by "
        f"a build receipt (`scheduler.py report` replaces `notes` wholesale); "
        f"the other {blank} carry no method evidence this tool will accept, "
        f"which is a weaker claim than saying they are empty. Recoverable "
        f"going forward, not for these records; `match_provenance.py "
        f"--unknown` lists them.",
        f"- **The categories overlap.** Each match is counted once, by "
        f"whichever step was DECISIVE. The model fleet is sole author of "
        f"{fleet_sole} but contributed to {fleet_touched}; a model draft the "
        f"permuter drove to zero counts as `permuter`, deliberately, because "
        f"crediting the model would overstate the fleet.",
        f"- **`transplant` is separate from `twin-port` on purpose.** Both "
        f"move a body from a sibling overlay, but a twin-port had its "
        f"divergences worked out by hand while a transplant was placed "
        f"mechanically with the substitutions derived from an asm diff. They "
        f"need different follow-up, so they are not pooled.",
    ]
    lines.append(PROV_END)
    return "\n".join(lines)


def splice(text: str, begin: str, end: str, block: str) -> str:
    """Replace between markers. Missing markers is an ERROR, not an append.

    Appending would silently produce two status tables, and the stale one
    would keep being read. Say the markers are absent and change nothing.
    """
    i, j = text.find(begin), text.find(end)
    if i < 0 or j < 0 or j < i:
        raise LookupError(f"markers {begin} .. {end} not found in README.md")
    return text[:i] + block + text[j + len(end):]


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--write", action="store_true",
                    help="update README.md in place; otherwise just print")
    ap.add_argument("--self-test", action="store_true")
    a = ap.parse_args()
    if a.self_test:
        return self_test()

    sb, pb = status_block(), provenance_block()
    if not a.write:
        print(sb + "\n\n" + pb)
        print("\n(nothing written; pass --write)")
        return 0
    text = README.read_text(encoding="utf-8")
    try:
        text = splice(text, STATUS_BEGIN, STATUS_END, sb)
        text = splice(text, PROV_BEGIN, PROV_END, pb)
    except LookupError as e:
        print(f"refused: {e}", file=sys.stderr)
        return 1
    README.write_text(text, encoding="utf-8")
    print("README.md updated")
    return 0


def self_test() -> int:
    fails = []

    def ck(c, label, detail=""):
        print(("  ok   " if c else "  FAIL ") + label
              + ("" if c else "   " + detail))
        if not c:
            fails.append(label)

    print("\nsplice replaces between markers and is idempotent")
    doc = f"before\n{STATUS_BEGIN}\nold\n{STATUS_END}\nafter\n"
    once = splice(doc, STATUS_BEGIN, STATUS_END,
                  f"{STATUS_BEGIN}\nnew\n{STATUS_END}")
    ck("new" in once and "old" not in once, "the block is replaced")
    ck(once.startswith("before") and once.rstrip().endswith("after"),
       "and the surrounding prose survives")
    twice = splice(once, STATUS_BEGIN, STATUS_END,
                   f"{STATUS_BEGIN}\nnew\n{STATUS_END}")
    ck(twice == once, "running it again changes nothing")

    print("\nmissing markers REFUSE rather than appending a second table")
    # Appending would leave two status tables and the stale one would keep
    # being read, which is the failure this tool exists to end.
    try:
        splice("no markers here", STATUS_BEGIN, STATUS_END, "x")
        ck(False, "absent markers raise")
    except LookupError:
        ck(True, "absent markers raise")

    print("\nthe README carries the markers this tool needs")
    txt = README.read_text(encoding="utf-8")
    for mk in (STATUS_BEGIN, STATUS_END, PROV_BEGIN, PROV_END):
        ck(mk in txt, f"{mk} present")

    print("\nthe queue row is never rendered empty")
    # `scheduler.py stats` writes `total 470` space-separated and every other
    # row as `   todo: 126`. The first regex required whitespace, matched only
    # `total`, and the table shipped as "470 records:" with nothing after the
    # colon. Assert against the REAL command, not a fixture: the format is the
    # thing that broke.
    q = queue_counts()
    ck(q.get("total", 0) > 0, f"total parsed ({q.get('total')})")
    ck(q.get("matched", 0) > 0, f"matched parsed ({q.get('matched')})")
    ck(len(q) >= 5, f"every status row parsed, not just total ({sorted(q)})")
    ck("records:" not in status_block().split("| Queue |")[1].split("|")[0]
       .replace("records:", "records: ").strip()[-1:],
       "the queue cell is not left dangling after the colon")

    print("\nstubs are counted for the `us` build only")
    # Counting every .c under src/ took this from 775 to 2734, four fifths of
    # it Saturn -- a port by an external team that the queue, the oracle and
    # every other number in this README exclude. A status line that silently
    # changes what it counts looks like progress in reverse.
    total, per = stub_counts()
    ck("saturn" not in per, f"saturn is excluded ({sorted(per)})")
    ck(not any(k.endswith("_psp") for k in per),
       f"and the psp trees are too ({sorted(per)})")
    # NO MAGIC RANGE. My first version asserted 400 < total < 1500, a window
    # drawn around the stale 775 -- which was itself inconsistent, since its
    # own per-area figures summed to 592. Encoding a guessed number in the
    # test for a tool whose whole purpose is to stop guessed numbers is the
    # same mistake one layer up. Assert the SHAPE instead: the areas are the
    # us ones, and the parts add up to the whole.
    ck(total > 0 and set(per) <= {"st", "boss", "main", "servant", "dra",
                                  "ric", "weapon"},
       f"only us build areas are counted ({sorted(per)})")
    ck(total == sum(per.values()),
       f"and the total is the sum of its parts ({total} vs "
       f"{sum(per.values())}), which the old hand-written 775 was not")

    print("\ninventory counts are DISCOVERED, never written down")
    inv = inventory()
    ck(inv["modules"] > 40, f"modules counted ({inv['modules']})")
    ck(inv["suites"] > 15, f"test suites counted ({inv['suites']})")
    ck(inv["tools"] > 40, f"connector tools counted ({inv['tools']})")
    ck(inv["diagnostics"] > 40, f"diagnostics counted ({inv['diagnostics']})")
    src_self = Path(__file__).read_text(encoding="utf-8")
    ck("ANALYSIS_SCRIPTS" in src_self,
       "diagnostics read the real registry, not a literal")

    print("\nthe oracle is READ, never run")
    # A generator that triggers a build would take minutes and need the lock.
    #
    # TEST WHAT IS SPAWNED, NOT WHAT IS SPELLED. The first version forbade the
    # words "make build" anywhere in the file and then failed on its own help
    # text -- the absent-artifacts message says `run make build then re-run`,
    # which is advice, not an invocation. Grepping prose for a verb catches
    # documentation as often as behaviour.
    spawned = re.findall(r"_run\(\[([^\]]*)\]", src_self)
    ck(spawned, f"the subprocess call sites are findable ({len(spawned)})")
    ck(all("scheduler.py" in s for s in spawned),
       f"and every one of them runs scheduler.py, nothing else ({spawned})")
    ck("verify_checksums" in src_self,
       "the oracle is read by hashing artifacts already on disk")

    print("\nand a missing build is reported, not papered over")
    ck("no build artifacts on disk" in src_self,
       "the absent-artifact case has its own message")

    print("\nthe queue is read through the scheduler")
    # THE NEEDLE IS BUILT FROM PARTS. Written literally, the assertion line
    # itself contains "queue" + ".jsonl", so the check finds its own source
    # and fails no matter what the module does. That is the fourth time this
    # exact trap has fired in this repo today; see the dashboard parse check
    # in test_connector_surfaces and _strip_comments_and_strings in
    # worker_direct for the others.
    needle = "queue" + ".jsonl"
    ck("scheduler.py" in src_self, "the scheduler is invoked")
    ck(needle not in src_self, "and the queue file is never opened directly")

    print()
    if fails:
        print(f"{len(fails)} FAILED:")
        for f in fails:
            print("  - " + f)
        return 1
    print("all checks passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
